### ISSUE TITLE
Error getting HTML in a more complicated use case

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#1021]
Let me look into this:
```
[2019-12-09 18:55:56] INFO: Start to measure search
[2019-12-09 18:56:05] ERROR: Could not find a matching resource to get the HTML Error: No resource with given identifier found
    at /usr/src/app/node_modules/chrome-remote-interface/lib/chrome.js:93:35
    at Chrome._handleMessage (/usr/src/app/node_modules/chrome-remote-interface/lib/chrome.js:256:17)
    at WebSocket.<anonymous> (/usr/src/app/node_modules/chrome-remote-interface/lib/chrome.js:234:22)
    at WebSocket.emit (events.js:210:5)
    at WebSocket.EventEmitter.emit (domain.js:476:20)
    at Receiver.receiverOnMessage (/usr/src/app/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:210:5)
    at Receiver.EventEmitter.emit (domain.js:476:20)
    at Receiver.dataMessage (/usr/src/app/node_modules/ws/lib/receiver.js:422:14)
    at /usr/src/app/node_modules/ws/lib/receiver.js:379:23
    at /usr/src/app/node_modules/ws/lib/permessage-deflate.js:298:9
    at /usr/src/app/node_modules/ws/lib/permessage-deflate.js:376:7
    at afterWrite (_stream_writable.js:501:3)
    at onwrite (_stream_writable.js:488:7)
    at InflateRaw.afterTransform (_stream_transform.js:96:3)
    at Zlib.processCallback (zlib.js:571:8)

```

**Comment by soulgalore** [comment]
This has been fixed by that we test the following request/respone and try to find the right one.
