### ISSUE TITLE
Window recorder doesn't work

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#1027]
Testing on Firefox 72:
` --firefox.windowRecorder --video https://www.sitespeed.io -n 1 -b firefox`

generates 

```
[2019-12-12 07:57:40] ERROR: JavascriptError: ReferenceError: windowUtils is not defined
    at Object.throwDecodedError (/Users/phedenskog/git/browsertime/node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/Users/phedenskog/git/browsertime/node_modules/selenium-webdriver/lib/http.js:560:13)
    at Executor.execute (/Users/phedenskog/git/browsertime/node_modules/selenium-webdriver/lib/http.js:486:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

Hi @brennie I think something went wrong with https://github.com/sitespeedio/browsertime/pull/995 ?

**Comment by brennie** [comment]
Hi! I'm investigating this and will hopefully have a fix to you today.

**Comment by soulgalore** [comment]
Fixed in https://github.com/sitespeedio/browsertime/pull/1037
