### ISSUE TITLE
 Contentful Speed Index's visualmetrics.py broken on convert call on macOS

### ISSUE THREAD

**Issue by tarekziade** [sitespeedio/browsertime#1091]
when visualmetrics is processing the data for the contentful speed index it breaks
with all versions of ImageMagick (6.x, 7.x) because it fails to parse the convert result.

For example, this call:

```
convert browsertime-results/google.com/2020-01-09T143331+0100/pages/google.com/data/video/images/3/ms_001400.png -canny 2x2+8%+8% -define histogram:unique-colors=true -format %c histogram:info:-'
```

returns 

```
     80883: (0,0,0) #000000 gray(0)
       317: (65535,65535,65535) #FFFFFF gray(255)
```

and that leads to 

```
Traceback (most recent call last):
  File "/Users/tarek/Dev/gecko/mozilla-central-opt/tools/browsertime/node_modules/browsertime/vendor/visualmetrics.py", line 1909, in main
    options.herodata)
  File "/Users/tarek/Dev/gecko/mozilla-central-opt/tools/browsertime/node_modules/browsertime/vendor/visualmetrics.py", line 1330, in calculate_visual_metrics
    value, value_progress = calculate_contentful_speed_index(progress, dirs)
  File "/Users/tarek/Dev/gecko/mozilla-central-opt/tools/browsertime/node_modules/browsertime/vendor/visualmetrics.py", line 1493, in calculate_contentful_speed_index
    value  = int(output.split()[7].split(':')[0])
ValueError: invalid literal for int() with base 10: 'gray(255)'
```

@soulgalore  Would it make sense to extract X from gray(X) via a regexp here ?
Happy to do this.

**Comment by soulgalore** [comment]
@tarekziade yeah feel free to that, I've not  touched Contentful speed index. We also have #1013 that happens on Linux that it would be great to get some help with :)
