### ISSUE TITLE
Timeout errors from screenshoot in Chrome 79

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#1106]
When we get errors on the test server it starts with:
```
[2020-01-12 19:16:18] WARN: Failed to take screenshot TimeoutError: timeout: Timed out receiving message from renderer: 10.000
  (Session info: chrome=79.0.3945.117)
  (Session info: chrome=79.0.3945.117)
    at Object.throwDecodedError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:563:13)
    at Executor.execute (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:489:26)
```

and then follows 
```
[2020-01-12 19:21:20] INFO: URL failed to load, trying 2 more time(s): Failed running the PageCompleteCheck 
[2020-01-12 19:26:21] ERROR: Failed running the PageCompleteCheck:Running page complete check 
return (function(waitTime) {
  const timing = window.performance.timing;
  const p = window.performance;
  const resourceTimings = p.getEntriesByType('resource');
  if (resourceTimings.length > 0) {
    const lastEntry = resourceTimings.pop();
    const stop = p.now() - lastEntry.responseEnd > waitTime;
    if (stop) {
      // empty resource timings for the next run
      p.clearResourceTimings();
      return true;
    }
  }
  else return false;
})(arguments[arguments.length - 1]);
 took too long
```

It looks like Chrome/Chromedriver comes in bad state. Best case its **ChromeDriver may block indefinitely while waiting for pending navigation**  in https://chromedriver.storage.googleapis.com/80.0.3987.16/notes.txt

**Comment by soulgalore** [comment]
The symptoms are the same as in https://bugs.chromium.org/p/chromedriver/issues/detail?id=2117 but that is fixed and should only happen when alerts fires when taking a screenshot.

**Comment by soulgalore** [comment]
I was ale to reproduce with the Chromedriver log turned on and created an upstream issue: https://bugs.chromium.org/p/chromedriver/issues/detail?id=3307

**Comment by soulgalore** [comment]
Upgrading to Chrome 80 beta has fixed those issues!
