### ISSUE TITLE
Failure of document height escalates into full run failure

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#1154]
This happens on our test server. The JS that runs to collect document height fails, and then it escalates to a failure so in sitespeed.io the result HTML isn't produced.

```
[2020-01-29 09:57:54] ERROR: Couldn't execute script named documentHeight error:JavascriptError: javascript error: Cannot read property 'scrollHeight' of null
  (Session info: chrome=80.0.3987.53)
[2020-01-29 09:57:54] ERROR: Failed to execute user script: JavascriptError: javascript error: Cannot read property 'scrollHeight' of null
  (Session info: chrome=80.0.3987.53)
[2020-01-29 09:57:55] ERROR: Visual Metrics failed to analyse the video TypeError: Cannot read property 'visualElements' of undefined
    at Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:213:49)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:124:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:125:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:134:24)
[2020-01-29 09:57:55] ERROR: TypeError: Cannot read property 'push' of undefined
    at Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:235:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:124:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:125:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:134:24)
[2020-01-29 09:57:55] ERROR: Error: Unhandled value type undefined found when adding data for pageinfo
    at addRecursive (/usr/src/app/node_modules/browsertime/lib/support/statistics.js:106:17)
    at /usr/src/app/node_modules/browsertime/lib/support/statistics.js:87:15
    at Array.forEach (<anonymous>)
    at addRecursive (/usr/src/app/node_modules/browsertime/lib/support/statistics.js:85:32)
    at Statistics.addDeep (/usr/src/app/node_modules/browsertime/lib/support/statistics.js:115:5)
    at Collector.perIteration (/usr/src/app/node_modules/browsertime/lib/core/engine/collector.js:132:20)
    at Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:128:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:125:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:134:24)
```

**Comment by ncalexan** [comment]
I see this while trying to get v8-alpha working against mozilla-central: see, for example [this job](https://treeherder.mozilla.org/#/jobs?repo=try&tier=1%2C2%2C3&revision=1d1acb8ae959f72d6dedc5a73cd970f85083ce6f&selectedJob=287032604) which fails with:
```
1580433791406 webdriver::server DEBUG <- 500 Internal Server Error {"value":{"error":"javascript error","message":"TypeError: can't access property \"scrollHeight\", body is null","stacktrace":"docHeight@https://www.amazon.com/:7:1\n@https://www.amazon.com/:15:10\n@https://www.amazon.com/:16:3\n@https://www.amazon.com/:18:8\n"}}
[2020-01-31 01:23:11] ERROR: [browsertime] Couldn't execute script named documentHeight error:JavascriptError: TypeError: can't access property "scrollHeight", body is null
[2020-01-31 01:23:11] ERROR: [browsertime] Failed to execute user script: JavascriptError: TypeError: can't access property "scrollHeight", body is null
raptor-main Critical: TEST-UNEXPECTED-FAIL: no raptor test results were found for amazon-cold
```

**Comment by ncalexan** [comment]
I'll bump our SHA to pick up my URL comparison fixes and see if this still occurs.

**Comment by soulgalore** [comment]
I think there are a couple of things here: First the actual failure, that seems that the page wasn't loaded right (running https://github.com/sitespeedio/browsertime/blob/master/browserscripts/pageinfo/documentHeight.js)? But I'm not sure either how that escalates that it throws an error and not continuing with the rest of the JS. 

What I fixed was a two later failures. I was seeing the error on https://m.world.taobao.com.

**Comment by soulgalore** [comment]
I think this is fixed.

**Comment by Sourick93** [comment]
@soulgalore I m facing this similar issue, What was the fix in this case ?
