### ISSUE TITLE
Contentful Speed Index throws error

### ISSUE THREAD

**Issue by jdmchone** [sitespeedio/browsertime#1205]
Using CentOS 7, and git cloned the latest sitespeed.io version 12.0.1 from 11.9.3. I have everything installed and working (ffmpeg, visualmetrics, chromedriver, chrome 80, firefox 72, etc...). 

When I run a test, i get the following error:
RROR: Could not generate url/summary/index
[2020-02-20 05:30:53] ERROR: TypeError: /root/sitespeed.io/lib/plugins/html/templates/url/metrics/index.pug:32
    30|             td
    31|               a(href=baseHelpURL + 'ContentfulSpeedIndex') Contentful Speed Index
  > 32|             td.number #{h.time.ms(visualMetrics.ContentfulSpeedIndex.toFixed(0))}
    33|           if visualMetrics.LargestImage
    34|             tr
    35|               td

Cannot read property 'toFixed' of null
    at eval (eval at wrap (/root/sitespeed.io/node_modules/pug/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2958:102)
    at template (eval at wrap (/root/sitespeed.io/node_modules/pug/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:6849:201)
    at Object.renderTemplate (/root/sitespeed.io/lib/plugins/html/renderer.js:28:39)
    at HTMLBuilder._renderUrlPage (/root/sitespeed.io/lib/plugins/html/htmlBuilder.js:402:16)
    at HTMLBuilder.render (/root/sitespeed.io/lib/plugins/html/htmlBuilder.js:311:18)

Not sure what's wrong. All version up to 11.9.3 work, but when i try to use the later version, it doesn't.

**Comment by soulgalore** [comment]
Thanks for the log @jdmchone  ... there where some fixes that hasn't been released, could you just verify that you get the issue with the unreleased version too?

Change docker container to use `sitespeedio/sitespeed.io-autobuild:latest` or ahh I see now, you using the latest in git right? Do a git pull and make sure you use Browsertime 8.1.0 (in your logs it was 8.0.1).

**Comment by jdmchone** [comment]
The original logs i sent were older Browsertime. But the visual metrics log was using Browsertime 8.1.0, nodejs 12.16.1, Chrome 80, Firefox 72, and the latest sitespeed.io direct from the repo. I will attach the latest visual metric log. 

/start.sh -n 1 https://sitespeed.io
Google Chrome 80.0.3987.116 
Mozilla Firefox 72.0
[2020-02-21 15:11:33] INFO: Versions OS: linux 4.19.76-linuxkit nodejs: v12.16.1 sitespeed.io: 12.0.1 browsertime: 8.1.0 coach: 4.4.1

**Comment by jdmchone** [comment]
[1.visualmetrics.log](https://github.com/sitespeedio/browsertime/files/4236701/1.visualmetrics.log)

**Comment by jdmchone** [comment]
I noticed you made some changes, yesterday, to the Browsertime repo. I'll do another pull for sitespeedio git repo and see if there is any changes.

**Comment by jdmchone** [comment]
Ok. Pulled down the latest sitespeed.io repo and ran test again. Getting the same error in Visualmetrics:

15:29:04.434 - contentfulSpeedIndex: Current Image is /root/sitespeed-result/sitespeed.io/2020-02-21-15-28-50/pages/sitespeed.io/data/filmstrip/1/ms_000702.png
15:29:04.447 - Command 'convert /root/sitespeed-result/sitespeed.io/2020-02-21-15-28-50/pages/sitespeed.io/data/filmstrip/1/ms_000702.png -canny 2x2+8%+8% -define histogram:unique-colors=true -format %c histogram:info:-' returned non-zero exit status 1
Traceback (most recent call last):
  File "/usr/local/share/.config/yarn/global/node_modules/browsertime/browsertime/visualmetrics.py", line 1667, in calculate_contentful_speed_index
    output = subprocess.check_output(command, shell=True).decode('utf-8')
  File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'convert /root/sitespeed-result/sitespeed.io/2020-02-21-15-28-50/pages/sitespeed.io/data/filmstrip/1/ms_000702.png -canny 2x2+8%+8% -define histogram:unique-colors=true -format %c histogram:info:-' returned non-zero exit status 1
15:29:04.448 - Hero elements file is not valid: None
15:29:04.448 - Converting video frames to JPEG
15:29:04.449 - mogrify -format jpg -set colorspace sRGB -quality 75 "/root/sitespeed-result/sitespeed.io/2020-02-21-15-28-50/pages/sitespeed.io/data/filmstrip/1/ms_*.png"
15:29:04.468 - Done Converting video frames to JPEG

**Comment by jdmchone** [comment]
[1.visualmetrics.log](https://github.com/sitespeedio/browsertime/files/4236756/1.visualmetrics.log)
 
Versions OS: linux 4.19.76-linuxkit nodejs: v12.16.1 sitespeed.io: 12.0.1 browsertime: 8.1.0 coach: 4.5.0

**Comment by jdmchone** [comment]
Also, we're seeing that our scripted tests, that worked with sitespeed.io version 11.9.3 and previous, don't work in 12.0.1 with updated browsertime. Getting the following errors. Not sure it it's related. If you need me to, i'll create a separate issue for this (we redacted the sitenames and selector names):

[2020-02-21 15:30:33] INFO: Versions OS: linux 4.9.184-linuxkit nodejs: v12.16.1 sitespeed.io: 12.0.1 browsertime: 8.1.0 coach: 4.4.1
[2020-02-21 15:30:34] INFO: Will run Lighthouse tests after Browsertime has finished
[2020-02-21 15:30:34] INFO: GPSI can only be used on URLs and not with scripting/multiple pages at the moment
[2020-02-21 15:30:34] INFO: Lighthouse can only be used on URLs and not with scripting/multiple pages at the moment
[2020-02-21 15:30:35] INFO: Running tests using Chrome - 1 iteration(s)
[2020-02-21 15:30:35] INFO: Start to measure {oursitename} Checkout
[2020-02-21 15:30:36] INFO: {oursitename} Test w/ SitespeedIO 12
[2020-02-21 15:30:36] INFO: Navigating to url {oursitename}
[2020-02-21 15:30:44] INFO: Send {our-custom-id}
[2020-02-21 15:30:44] INFO: Search for {our-custom-id}
[2020-02-21 15:30:44] INFO: Click on the Image
[2020-02-21 15:30:44] ERROR: Couldn't execute script named CUSTOM error:JavascriptError: javascript error: Cannot read property 'click' of null
  (Session info: chrome=80.0.3987.116)
[2020-02-21 15:30:44] ERROR: Could not click using selector [{our-custom-selector}]
[2020-02-21 15:30:44] ERROR: Error: Could not click using selector [{our-custom-selector}]
    at Click.bySelectorAndWait (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/engine/command/click.js:242:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-02-21 15:30:44] ERROR: ReferenceError: command is not defined
    at module.exports (/sitespeed.io/tests/{oursitename}.js:18:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-02-21 15:30:44] ERROR: No data to collect
[2020-02-21 15:30:45] ERROR: TypeError: Cannot read property 'alias' of undefined
    at Object.processMessage (/usr/local/share/.config/yarn/global/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:149:50)
[2020-02-21 15:30:45] INFO: HTML stored in /results/sitespeed-result/{oursitename}_js/2020-02-21-15-30-33

**Comment by soulgalore** [comment]
@jdmchone yes please create another issue, that looks like something else. Nothing should have changed in the commands structure in scripting between releases so curios finding out what's the problem.

**Comment by jdmchone** [comment]
Done. Other issue created.
