### ISSUE TITLE
Scripted checks not working beyond sitespeed.io version 11.9.3

### ISSUE THREAD

**Issue by jdmchone** [sitespeedio/browsertime#1207]
We're seeing an issue when running scripted tests after pulling the latest git repo for sitespeed.io. Our tests work with sitespeed.io version 11.9.3 and previous, but don't work in 12.0.1 with updated browsertime (8.1.0). Getting the following errors (we redacted the sitenames and selector names):

[2020-02-21 15:30:33] INFO: Versions OS: linux 4.9.184-linuxkit nodejs: v12.16.1 sitespeed.io: 12.0.1 browsertime: 8.1.0 coach: 4.4.1
[2020-02-21 15:30:34] INFO: Will run Lighthouse tests after Browsertime has finished
[2020-02-21 15:30:34] INFO: GPSI can only be used on URLs and not with scripting/multiple pages at the moment
[2020-02-21 15:30:34] INFO: Lighthouse can only be used on URLs and not with scripting/multiple pages at the moment
[2020-02-21 15:30:35] INFO: Running tests using Chrome - 1 iteration(s)
[2020-02-21 15:30:35] INFO: Start to measure {oursitename} Checkout
[2020-02-21 15:30:36] INFO: {oursitename} Test w/ SitespeedIO 12
[2020-02-21 15:30:36] INFO: Navigating to url {oursitename}
[2020-02-21 15:30:44] INFO: Send {our-custom-id}
[2020-02-21 15:30:44] INFO: Search for {our-custom-id}
[2020-02-21 15:30:44] INFO: Click on the Image
[2020-02-21 15:30:44] ERROR: Couldn't execute script named CUSTOM error:JavascriptError: javascript error: Cannot read property 'click' of null
(Session info: chrome=80.0.3987.116)
[2020-02-21 15:30:44] ERROR: Could not click using selector [{our-custom-selector}]
[2020-02-21 15:30:44] ERROR: Error: Could not click using selector [{our-custom-selector}]
at Click.bySelectorAndWait (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/engine/command/click.js:242:13)
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-02-21 15:30:44] ERROR: ReferenceError: command is not defined
at module.exports (/sitespeed.io/tests/{oursitename}.js:18:5)
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-02-21 15:30:44] ERROR: No data to collect
[2020-02-21 15:30:45] ERROR: TypeError: Cannot read property 'alias' of undefined
at Object.processMessage (/usr/local/share/.config/yarn/global/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:149:50)
[2020-02-21 15:30:45] INFO: HTML stored in /results/sitespeed-result/{oursitename}_js/2020-02-21-15-30-33

**Comment by soulgalore** [comment]
Hi @jdmchone can you show me more exactly where it fails, what you do so I can try to reproduce?

**Comment by jdmchone** [comment]
Nevermind. Figured it out. Let you decide if you want to delete this issue or not. 
So, in older versions of browsertime, you could use "s or 's for things like **bySelector("selectorname");** or **bySelector('selectorname');**. But, that was fixed in browsertime 8.* and so we needed to update all of our scripting, accordingly. It's a cleaner approach that trying to use both, and using "s would require you to escape them when dealing with class identifiers...like **bySelector("selectorname=\"value\"");**, which doesn't work now, as it should be 's instead like **bySelector('selectorname="value"');**
