### ISSUE TITLE
Crawling on Chrome in Android breaks devtools port

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#1239]
The errors is from sitespeed.io but my guess is that the bug is somewhere in Browsertime.

```
bin/sitespeed.js https://en.wikipedia.org/wiki/Main_Page --android -d 2 -n 1
[2020-04-15 13:55:13] INFO: Versions OS: darwin 19.4.0 nodejs: v10.15.3 sitespeed.io: 12.5.1 browsertime: 8.6.0 coach: 5.0.1
[2020-04-15 13:55:13] INFO: Starting to crawl from https://en.wikipedia.org/wiki/Main_Page with max depth 2 and max count 9007199254740991
[2020-04-15 13:55:13] INFO: Running tests using Chrome - 1 iteration(s)
[2020-04-15 13:55:21] INFO: Testing url https://en.wikipedia.org/wiki/Main_Page iteration 1
[2020-04-15 13:55:32] INFO: https://en.wikipedia.org/wiki/Main_Page 29 requests, backEndTime: 305ms, firstPaint: 1.11s, FCP: 1.11s, DOMContentLoaded: 663ms, LCP: 1.11s, Load: 1.03s
[2020-04-15 13:55:32] INFO: Running tests using Chrome - 1 iteration(s)
[2020-04-15 13:55:37] ERROR: Error: connect ECONNREFUSED 127.0.0.1:9229
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
[2020-04-15 13:55:38] ERROR: No data to collect
[2020-04-15 13:55:38] ERROR: TypeError: Cannot read property 'close' of undefined
    at ChromeDevtoolsProtocol.close (/Users/phedenskog/git/sitespeed.io/node_modules/browsertime/lib/chrome/webdriver/chromeDevtoolsProtocol.js:178:27)
    at ChromeDelegate.onStop (/Users/phedenskog/git/sitespeed.io/node_modules/browsertime/lib/chrome/webdriver/chromeDelegate.js:445:28)
    at Engine.runByScript (/Users/phedenskog/git/sitespeed.io/node_modules/browsertime/lib/core/engine/index.js:146:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by soulgalore** [comment]
Coming in next release.
