### ISSUE TITLE
Unhandled data for Firefox

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#1261]
```
[2020-04-29 04:09:18] INFO: Testing url https://en.m.wikipedia.org/speed-tests/Banksy.enwiki.872156204/ iteration 1
[2020-04-29 04:09:24] INFO: Waiting on har-export-trigger to collect the HAR
[2020-04-29 04:09:26] ERROR: TypeError: Cannot convert undefined or null to object
    at FirefoxDelegate.afterCollect (/usr/src/app/node_modules/browsertime/lib/firefox/webdriver/firefoxDelegate.js:219:41)
```

**Comment by soulgalore** [comment]
Released a fix but it's still an issue:
```
[2020-04-30 08:13:58] ERROR: TypeError: Cannot read property 'appConstants' of undefined
    at FirefoxDelegate.afterCollect (/usr/src/app/node_modules/browsertime/lib/firefox/webdriver/firefoxDelegate.js:221:46)
```

It looks like sometimes we don't get any JS from Firefox. Yesterday I couldn't reproduce it, lets see if I can try it again.

**Comment by soulgalore** [comment]
After another fix this seems to be fixed.
