### ISSUE TITLE
Catch NoSuchSessionError for Safari

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#1274]
Running many runs for Safari on iOS sometimes fails:

```
[2020-05-06 20:39:22] INFO: Testing url https://en.m.wikipedia.org/wiki/Barack_Obama iteration 41
[2020-05-06 20:39:29] ERROR: Failed to take screenshot for https://en.m.wikipedia.org/wiki/Barack_Obama WebDriverError
    at Object.throwDecodedError (/Users/phedenskog/git/sitespeed.io/node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/Users/phedenskog/git/sitespeed.io/node_modules/selenium-webdriver/lib/http.js:565:13)
    at Executor.execute (/Users/phedenskog/git/sitespeed.io/node_modules/selenium-webdriver/lib/http.js:491:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-05-06 20:39:29] ERROR: Couldn't execute script named documentHeight error:NoSuchSessionError
[2020-05-06 20:39:29] ERROR: Failed to execute user script: NoSuchSessionError
[2020-05-06 20:39:29] ERROR: Couldn't execute script named elementTimings error:NoSuchSessionError
[2020-05-06 20:39:29] ERROR: Failed to execute user script: NoSuchSessionError
[2020-05-06 20:39:29] ERROR: Couldn't execute script named RESOURCE_TIMINGS error:NoSuchSessionError
[2020-05-06 20:39:29] ERROR: NoSuchSessionError
    at Object.throwDecodedError (/Users/phedenskog/git/sitespeed.io/node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/Users/phedenskog/git/sitespeed.io/node_modules/selenium-webdriver/lib/http.js:565:13)
    at Executor.execute (/Users/phedenskog/git/sitespeed.io/node_modules/selenium-webdriver/lib/http.js:491:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-05-06 20:39:29] ERROR: TypeError: Cannot read property 'length' of undefined
    at Collector.perIteration (/Users/phedenskog/git/sitespeed.io/node_modules/browsertime/lib/core/engine/collector.js:115:31)
    at Engine.runByScript (/Users/phedenskog/git/sitespeed.io/node_modules/browsertime/lib/core/engine/index.js:154:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-05-06 20:39:29] INFO: HTML stored in /Users/phedenskog/git/sitespeed.io/sitespeed-result/en.m.wikipedia.org/2020-05-06-20-31-31
```

It can fail that's ok but we should continue to try another run or what happens with  _NoSuchSessionError_? In this example I tried to do 75 runs.

**Comment by soulgalore** [comment]
We have bigger problems with Safari and WebDriver at the moment so lets close this.
