### ISSUE TITLE
TypeError: Cannot set property 'variance' of undefined

### ISSUE THREAD

**Issue by mploquin** [sitespeedio/browsertime#1326]
Hi,

When i run my tests with throttle engine, i have an error **TypeError: Cannot set property 'variance' of undefined**  with somes connectivity profiles like dsl, fois, lte : 

`[2020-07-20 13:07:01] INFO: [sitespeedio] Versions OS: linux 5.4.0-40-generic nodejs: v12.16.2 sitespeed.io: 13.3.2 browsertime: 8.14.0 coach: 5.0.1
[2020-07-20 13:07:01] INFO: [sitespeedio] The following plugins are enabled: assets, axe, browsertime, budget, coach, domains, graphite, harstorer, html, metrics, pagexray, text, thirdparty, tracestorer, webpagetest, /lighthouse, /gpsi
[2020-07-20 13:07:02] INFO: [sitespeedio.plugin.axe] Axe plugin activated
[2020-07-20 13:07:03] INFO: [sitespeedio.plugin.lighthouse] Will run Lighthouse tests after Browsertime has finished
[2020-07-20 13:07:03] INFO: [sitespeedio.plugin.gpsi] Sending url https://xxx to test on Page Speed Insights
[2020-07-20 13:07:03] INFO: [sitespeedio.plugin.webpagetest] Sending url https://xxx to test on https://www.webpagetest.org
[2020-07-20 13:07:03] ERROR: [sitespeedio.queuehandler] TypeError: Cannot set property 'variance' of undefined
    at Object.parseTrafficShapeConfig (/usr/src/app/node_modules/browsertime/lib/connectivity/trafficShapeParser.js:125:24)
    at removeConnectivity (/usr/src/app/node_modules/browsertime/lib/connectivity/index.js:72:40)
    at Engine.stop (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:274:13)
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:129:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

This error not appears with others profiles like cable, 3g, 4g..

**Comment by soulgalore** [comment]
Hi @mploquin I think those profiles aren't existing in browsertime (see https://www.sitespeed.io/documentation/browsertime/configuration/) only in Throttle, so you need to create custom settings to get it to work.

**Comment by mploquin** [comment]
Thank you for your quick reply :rocket:  !
So it's not possible to use new profiles described in the file [here](https://github.com/sitespeedio/browsertime/blob/main/lib/connectivity/trafficShapeParser.js) ?

**Comment by soulgalore** [comment]
Apparently not :) It looks strange, I'll have a look when I find the time.

**Comment by mploquin** [comment]
Oups.. it works in fact with `newConnectivityProfiles` option
Maybe just add this option in the documentation

**Comment by soulgalore** [comment]
Yeah I think I somehow missed implementing everything before releasing this, let me have a look before I do the next release.

**Comment by soulgalore** [comment]
Ok, when I updated the connectivity profiles, I missed to make them default when we did a stable release. I'm doing that now for the coming the release.
