### ISSUE TITLE
Catch WebDriver timeout

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#138]
Seen this happen on Firefox (using sitespeed.io)
<pre>
/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/http/util.js:87
          Error('Timed out waiting for the WebDriver server at ' + url));
          ^
Error: Timed out waiting for the WebDriver server at http://127.0.0.1:48466/hub
    at Error (native)
    at onError (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/http/util.js:87:11)
    at ManagedPromise.invokeCallback_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/pro
mise.js:1379:14)
    at TaskQueue.execute_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:2913
:14)
    at TaskQueue.executeNext_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:
2896:21)
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:2775:27
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (node.js:369:9)
</pre>

We should catch that an wrap in Browserime error + should have longer stacktraces.

**Comment by tobli** [comment]
Should be fixed in 2024471.

**Comment by tobli** [comment]
Spoke too soon, still occurring in https://travis-ci.org/tobli/browsertime/jobs/132417087

**Comment by soulgalore** [comment]
Should we build a new one and push to DO or do you have more things you wanna push?

**Comment by tobli** [comment]
I don't have any additional fixes lined up right now. Need to take a deeper look at this.

**Comment by soulgalore** [comment]
wonder if maybe should catch Error in sitespeed.io for now since it seems like these things keep on jumping from Selenium.
