### ISSUE TITLE
Add video support for Safari on iOS

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#1406]

**Comment by jajo-shubham** [comment]
Hey @soulgalore . I recently tried to run visualMetrics on an **iPhone XS (13.4.1)** connected to a **mac mini(Catalina 10.15.5)**.  
Versions OS: darwin 19.5.0 nodejs: v10.16.3 sitespeed.io: 15.5.0 browsertime: 10.5.0 coach: 5.1.1

Command ran: `bin/sitespeed.js --safari.ios --safari.deviceUDID XXXXXXXX https://google.com https://google.com  --plugins.add analysisstorer  --visualMetrics  -vvv`

It errors out on the following line: 
```
[2020-10-19 14:41:01] INFO: [browsertime] Running tests using Safari - 3 iteration(s)
[2020-10-19 14:41:08] INFO: [browsertime.command.measure] Testing url https://google.com iteration 1
[2020-10-19 14:41:08] DEBUG: [browsertime.video] Add orange color
[2020-10-19 14:41:08] DEBUG: [browsertime.video] Getting screen on OS X using ["-hide_banner","-f","avfoundation","-list_devices",true,"-i",0]
[2020-10-19 14:41:08] DEBUG: [browsertime.video] Output: [AVFoundation indev @ 0x7fc26342a2c0] AVFoundation video devices:
[AVFoundation indev @ 0x7fc26342a2c0] [0] Capture screen 0
[AVFoundation indev @ 0x7fc26342a2c0] AVFoundation audio devices:
0: Input/output error
[2020-10-19 14:41:16] ERROR: [browsertime] Error: Command failed with exit code 1: system_profiler SPDisplaysDataType |grep Resolution
```

**Is this because there is no display attached to the mac mini or visual Metrics are just not supported right now on any iPhones?** 

 I bypassed this line by hardcoding some resolution and then it gave the following error:

```
[2020-10-19 15:25:16] INFO: [browsertime] Running tests using Safari - 3 iteration(s)
[2020-10-19 15:25:23] INFO: [browsertime.command.measure] Testing url https://google.com iteration 1
[2020-10-19 15:25:23] DEBUG: [browsertime.video] Add orange color
[2020-10-19 15:25:23] DEBUG: [browsertime.video] Getting screen on OS X using ["-hide_banner","-f","avfoundation","-list_devices",true,"-i",0]
[2020-10-19 15:25:23] DEBUG: [browsertime.video] Output: [AVFoundation indev @ 0x7fad26e04340] AVFoundation video devices:
[AVFoundation indev @ 0x7fad26e04340] [0] Capture screen 0
[AVFoundation indev @ 0x7fad26e04340] AVFoundation audio devices:
0: Input/output error
[2020-10-19 15:25:23] DEBUG: [browsertime.video] Start FFMPEG with ["-f","avfoundation","-i","0","-r",30,"-filter:v","crop=2732:1284:0:132","-codec:v","libx264rgb","-crf","0","-preset","ultrafast","/Users/app/FT/sitespeed.io/sitespeed-result/google.com/2020-10-19-15-25-16/x11-tmp.mp4"]
[2020-10-19 15:25:23] TRACE: [browsertime.video] ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
    at Socket.readableStream.on.data (/Users/app/FT/sitespeed.io/node_modules/browsertime/lib/video/screenRecording/desktop/ffmpegRecorder.js:76:13)
    at Socket.emit (events.js:203:15)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
[2020-10-19 15:25:23] TRACE: [browsertime.video]
  built with Apple clang version 12.0.0 (clang-1200.0.32.2)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.3.1_1 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100

    at Socket.readableStream.on.data (/Users/app/FT/sitespeed.io/node_modules/browsertime/lib/video/screenRecording/desktop/ffmpegRecorder.js:76:13)
    at Socket.emit (events.js:203:15)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
[2020-10-19 15:25:23] TRACE: [browsertime.video] [AVFoundation indev @ 0x7fe9e2c2a540] Configuration of video device failed, falling back to default.

    at Socket.readableStream.on.data (/Users/app/FT/sitespeed.io/node_modules/browsertime/lib/video/screenRecording/desktop/ffmpegRecorder.js:76:13)
    at Socket.emit (events.js:203:15)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
[2020-10-19 15:25:23] TRACE: [browsertime.video] [avfoundation @ 0x7fe9e3014600] Selected pixel format (yuv420p) is not supported by the input device.
[avfoundation @ 0x7fe9e3014600] Supported pixel formats:
[avfoundation @ 0x7fe9e3014600]   uyvy422
[avfoundation @ 0x7fe9e3014600]   yuyv422
[avfoundation @ 0x7fe9e3014600]   nv12
[avfoundation @ 0x7fe9e3014600]   0rgb
[avfoundation @ 0x7fe9e3014600]   bgr0
[avfoundation @ 0x7fe9e3014600] Overriding selected pixel format to use uyvy422 instead.

    at Socket.readableStream.on.data (/Users/app/FT/sitespeed.io/node_modules/browsertime/lib/video/screenRecording/desktop/ffmpegRecorder.js:76:13)
    at Socket.emit (events.js:203:15)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Also, Can you tell me why are we getting screen and resolution of OSX when the test is running on iPhone?**

**Comment by soulgalore** [comment]
This issue is about adding support for video on iOS. At the moment it doesn't work since we have not implemented it.

**Comment by soulgalore** [comment]
This has been released.
