### ISSUE TITLE
Firefox an Android freeze

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#1413]
I've been having problems with Firefox on Android where tests start to freeze and never recover. It runs on latest stable Firefox.

Been running the tests though the night and suddenly the tests stopped. Look at the time difference between the last log line and the rotation of the log:
```
[2020-10-20 19:36:25] INFO: URL failed to load, trying 0 more time(s): Failed waiting on page https://en.m.wikipedia.org/wiki/Main_Page  to finished loading, timed out after 300000 ms 
[2020-10-20 19:36:25] ERROR: Could not load URL https://en.m.wikipedia.org/wiki/Main_Page UrlLoadError: Failed waiting on page https://en.m.wikipedia.org/wiki/Main_Page  to finished loading, timed out after 300000 ms 
    at SeleniumRunner.wait (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:188:13)
[2020-10-20 19:36:25] ERROR: UrlLoadError: Failed to load https://en.m.wikipedia.org/wiki/Main_Page
    at SeleniumRunner.loadAndWait (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:313:17)
Oct 21 00:30:04 Mac-mini-156 newsyslog[27602]: logfile turned over
```

Looking for Marionette nothing happens:
```
10-20 19:05:44.549  8238  8268 I Gecko   : 1603235144548	Marionette	INFO	Stopped listening on port 2829
10-20 19:06:04.645  8830  8858 I Gecko   : 1603235164645	Marionette	INFO	Listening on port 2829
```

I could see that we have three geckodriver processes:
```
  501 81216     1   0  3:57PM ttys004    0:00.09 /usr/local/lib/node_modules/sitespeed.io/node_modules/@sitespeed.io/geckodriver/vendor/geckodriver --port=52811
  501 43112 28078   0  6:58PM ttys006    0:00.12 /usr/local/lib/node_modules/sitespeed.io/node_modules/@sitespeed.io/geckodriver/vendor/geckodriver --port=57256
  501 46032 28078   0  7:05PM ttys006    0:00.05 /usr/local/lib/node_modules/sitespeed.io/node_modules/@sitespeed.io/geckodriver/vendor/geckodriver --port=61735
```

That's two more than we should. I killed them `pkill geckodriver` and after a while the tests started again. Without me doing anything.

Let me go through the code and see what we do if the page fails to load and then turn on verbose logging and let it run again.

**Comment by soulgalore** [comment]
It is a finally block that should catch it but its many steps (and missing logs) so let me make a test case and add more logging to see if I can fix it.

**Comment by soulgalore** [comment]
I tested the code and it looks ok (=it closes the browser).

**Comment by soulgalore** [comment]
If this works, we can maybe do a follow at least for Android where we try to force stop the application using adb shell.

**Comment by soulgalore** [comment]
I think this works now.
