### ISSUE TITLE
RESOURCE_TIMINGS script errors out for certain particular websites

### ISSUE THREAD

**Issue by jajo-shubham** [sitespeedio/browsertime#1505]
Greetings @soulgalore !

The RESOURCE_TIMINGS script errors out for certain particular websites.. 
For example - on executing  `sitespeed.io -b safari  http://babytree.com -n 1 --visualMetrics `
> [2021-03-16 15:57:09] INFO: Versions OS: darwin 20.2.0 nodejs: v12.18.3 sitespeed.io: 16.9.2 browsertime: 11.5.0 coach: 6.1.0
[2021-03-16 15:57:09] INFO: Running tests using Safari - 1 iteration(s)
[2021-03-16 15:57:11] INFO: Testing url http://babytree.com iteration 1
[2021-03-16 15:57:35] ERROR: Couldn't execute script named RESOURCE_TIMINGS error:JavascriptError: A JavaScript exception occured: cannot serialize cyclic structures.
[2021-03-16 15:57:35] ERROR: JavascriptError: A JavaScript exception occured: cannot serialize cyclic structures.
    at Object.throwDecodedError (/Users/shubhamjajodia/.nvm/versions/node/v12.18.3/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/Users/shubhamjajodia/.nvm/versions/node/v12.18.3/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/http.js:671:13)
    at Executor.execute (/Users/shubhamjajodia/.nvm/versions/node/v12.18.3/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/http.js:597:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Driver.execute (/Users/shubhamjajodia/.nvm/versions/node/v12.18.3/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/webdriver.js:729:17)
    at async SeleniumRunner.runScript (/Users/shubhamjajodia/.nvm/versions/node/v12.18.3/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:370:22)
    at async Safari.afterPageCompleteCheck (/Users/shubhamjajodia/.nvm/versions/node/v12.18.3/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/safari/webdriver/safari.js:40:23)
    at async Measure.stop (/Users/shubhamjajodia/.nvm/versions/node/v12.18.3/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/command/measure.js:284:17)
    at async /Users/shubhamjajodia/.nvm/versions/node/v12.18.3/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/run.js:9:9
    at async Iteration.run (/Users/shubhamjajodia/.nvm/versions/node/v12.18.3/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/iteration.js:192:9)
    at async Engine.runByScript (/Users/shubhamjajodia/.nvm/versions/node/v12.18.3/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/index.js:258:20)
    at async Object.analyzeUrl (/Users/shubhamjajodia/.nvm/versions/node/v12.18.3/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:124:21)
    at async Object.processMessage (/Users/shubhamjajodia/.nvm/versions/node/v12.18.3/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:150:26)
[2021-03-16 15:57:35] INFO: http://babytree.com
[2021-03-16 15:57:37] INFO: HTML stored in /Users/shubhamjajodia/sitespeed-result/babytree.com/2021-03-16-15-57-09

Some further debugging showed me that this error is reproduced only on Big Sur, Safari (which I currently ran on) while the same runs for a catalina mac.   Also running the same test on chrome returns the handles the errored assests and prints them on the screen

**Comment by soulgalore** [comment]
Hi @jajo-shubham I see, thanks for creating the issue, can you create an upstream issue for Safari please? 

I verified and get the same, however running `performance.getEntriesByType("resource");` in the console I get the JSON back but I didn't look/see the cyclic structure. It would be great to see to make it easier to create a bug report.

**Comment by jajo-shubham** [comment]
Thanks for getting back!
Yeah it works for me too inside the console.. I think some assets are not loading in the resource entries which are skipped in the array on console but some assets are give 4xx due to which it tries to parse it for the log.  
Also I didnt  understand what you mean by **upstream** issue ? and why is it only there on big sur?

**Comment by soulgalore** [comment]
Sorry let me explain better! I think the bug is in Safari in their implementation in the resource timing API.  That what was I meant by upstream. It looks like `performance.getEntriesByType("resource");` then produces un-parsable JSON, I can have a look in a couple of days what's actually happens.

**Comment by jajo-shubham** [comment]
To me, it looks like an issue in `selenium-webdriver` . It is reproducible even for other browsers like chrome with this script when used `selenium-webdriver@4.0.0-beta.1` 
>const {Builder, By, Key, until} = require('selenium-webdriver');
const { ServiceBuilder } = require('selenium-webdriver/chrome');
const driverPath = '/Users/shubhamjajodia/Downloads/chromedriver'
const serviceBuilder = new ServiceBuilder(driverPath);
(async function example() {
  let browser = new Builder()
    .forBrowser('chrome')
    .setChromeService(serviceBuilder)
    .build();
  try {
    await browser.get('https://babytree.com')
    const element = await browser.executeScript('return performance.getEntriesByType("resource")') 
console.log(element);
  } finally {
    await browser.quit();
  }
})();

I am using chrome 89 and so passing the corresponding browser for that.  However I noticed today itself that in the next beta.2 update `selenium-webdriver@4.0.0-beta.2` , the same now works for chrome but is still broken for others like safari and firefox

**Comment by soulgalore** [comment]
I see I didn't try other version, can you please create an issue in the selenium repo, thanks!

**Comment by jajo-shubham** [comment]
Sure .. thanks @soulgalore

**Comment by soulgalore** [comment]
Thinking this has been fixed in Selenium? Please let me know if this is stil a problem.
