### ISSUE TITLE
New ADB kit causing error on Ubuntu in Docker

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#1517]
```
1-03-19 14:49:03] ERROR: TypeError: Cannot read property 'length' of null
    at tryRead (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/dist/src/adb/parser.js:178:42)
    at bluebird_1.default (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/dist/src/adb/parser.js:202:13)
    at Promise.cancellationExecute [as _execute] (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/debuggability.js:406:9)
    at Promise._resolveFromExecutor (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/promise.js:103:10)
    at Parser.readByteFlow (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/dist/src/adb/parser.js:171:16)
    at parser.readBytes.then (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/dist/src/adb/sync.js:250:48)
    at tryCatcher (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/async.js:15:14)
```

**Comment by soulgalore** [comment]
This seems to only happens when you run in Docker. Running Ubuntu works just fine.

**Comment by soulgalore** [comment]
I've added https://github.com/DeviceFarmer/adbkit/issues/94

**Comment by soulgalore** [comment]
Reverted the change, lets upgrade when the fixes been done in adbkit.
