### ISSUE TITLE
Chrome/Chromedriver 90 do not play nice on Mac OS

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#1548]
It seems to be some kind of bug that was introduced in 90:

```
❯ bin/browsertime.js https://www.sitespeed.io --connectivity.engine throttle -c cable --legacyConnectivityProfiles --chrome.enableChromeDriverLog --chrome.enableVerboseChromeDriverLog
[2021-04-16 15:40:32] INFO: Changing network interfaces needs sudo rights. Setting connectivity profile cable
[2021-04-16 15:40:33] INFO: Running tests using Chrome - 3 iteration(s)
[2021-04-16 15:40:47] INFO: Testing url https://www.sitespeed.io iteration 1
[2021-04-16 15:41:08] INFO: https://www.sitespeed.io TTFB: 342ms DOMContentLoaded: 572ms firstPaint: 583ms FCP: 583ms LCP: 1.09s Load: 1.41s 
[2021-04-16 15:41:23] INFO: Testing url https://www.sitespeed.io iteration 2
[2021-04-16 15:41:44] INFO: https://www.sitespeed.io TTFB: 380ms DOMContentLoaded: 597ms firstPaint: 612ms FCP: 612ms LCP: 1.22s Load: 1.26s 
[2021-04-16 15:41:44] INFO: chrome failed to start, trying 2 more time(s): Server terminated early with status 1
[2021-04-16 15:41:44] INFO: chrome failed to start, trying 1 more time(s): Server terminated early with status 1
[2021-04-16 15:41:44] INFO: chrome failed to start, trying 0 more time(s): Server terminated early with status 1
[2021-04-16 15:41:44] ERROR: BrowserError: Could not start chrome with 3 tries
    at SeleniumRunner.start (/Users/peter/git/browsertime/lib/core/seleniumRunner.js:86:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-04-16 15:41:44] ERROR: No data to collect

```

When I look in the chromdwriver log I get:
```
[1618580504.285][INFO]: Starting ChromeDriver 90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}) on port 50425
[1618580504.285][INFO]: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1618580504.287][SEVERE]: bind() failed: Address already in use (48)
[1618580504.288][INFO]: listen on IPv4 failed with error ERR_ADDRESS_IN_USE
```

But it only seems to happen when I throttle the connection. Let me investigate it.

**Comment by soulgalore** [comment]
It seems like with 90 Chrome isn't closed fast enough. Using a delay between runs fixes the problem:
`https://www.sitespeed.io -n 3 --connectivity.engine throttle -c cable -b chrome --delay 2000`

**Comment by soulgalore** [comment]
Its fixed on our side but I should create a bug for Chromedriver.
