### ISSUE TITLE
byJsAndWait function not working

### ISSUE THREAD

**Issue by ledleds** [sitespeedio/browsertime#1606]
Hello! Just raising this as a possible bug. I was having problems getting byJsAndWait working with the following code:

```
// sitespeedScript.js

module.exports = async function(context, commands) {
  // first navigate to landing page
  await commands.measure.start('http://host.docker.internal:3000/');
  // start a new measurement
  await commands.measure.start();
  await commands.click.byJsAndWait(`
    document.querySelector('[data-test-id="myTestId"]').querySelector("a");
  `);
  return commands.measure.stop();
};
```

I get the following error after running `docker run --shm-size 2g --rm -v "$(pwd):/sitespeed.io" --network=host sitespeedio/sitespeed.io:17.8.3 ./test/performance/sitespeedScript.js --multi -n 1 --html.summaryBoxes -b chrome`:

```
Google Chrome 91.0.4472.114
Mozilla Firefox 89.0
Microsoft Edge 91.0.864.11 dev
[2021-07-13 08:56:04] INFO: Versions OS: linux 5.10.25-linuxkit nodejs: v14.17.1 sitespeed.io: 17.8.3 browsertime: 12.10.0 coach: 6.4.2
[2021-07-13 08:56:04] INFO: Running tests using Chrome - 1 iteration(s)
[2021-07-13 08:56:05] INFO: Testing url http://host.docker.internal:3000/ iteration 1
[2021-07-13 08:56:17] INFO: Start to measure
[2021-07-13 08:56:18] ERROR: Couldn't execute script named CUSTOM error:JavascriptError: javascript error: Unexpected token '.'
  (Session info: chrome=91.0.4472.114)
[2021-07-13 08:56:18] ERROR: Could not find element by JavaScript
    document.querySelector('[data-test-id="myTestId"]').querySelector("a");

[2021-07-13 08:56:18] ERROR: Error: Could not find element by JavaScript
    document.querySelector('[data-test-id="myTestId"]').querySelector("a");

    document.querySelector('[data-test-id="myTestId"]').querySelector("a");

    at Click.byJsAndWait (/usr/src/app/node_modules/browsertime/lib/core/engine/command/click.js:184:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async module.exports (/sitespeed.io/test/performance/sitespeedScript.js:7:3)
    at async /usr/src/app/node_modules/browsertime/lib/core/engine/run.js:7:9
    at async Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:214:9)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:277:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:144:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:150:26)
[2021-07-13 08:56:18] ERROR: Caught error from Browsertime TypeError: Cannot read property 'split' of null
    at module.exports (/usr/src/app/node_modules/browsertime/lib/support/pathToFolder.js:23:42)
    at Collector.perIteration (/usr/src/app/node_modules/browsertime/lib/core/engine/collector.js:458:14)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:281:9)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:144:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:150:26)
[2021-07-13 08:56:18] ERROR: TypeError: Cannot read property 'split' of null
    at pathFromRootToPageDir (/usr/src/app/lib/core/resultsStorage/pathToFolder.js:20:40)
    at Object.relativeSummaryPageUrl (/usr/src/app/lib/core/resultsStorage/resultUrls.js:30:14)
    at DataCollector._addUrl (/usr/src/app/lib/plugins/html/dataCollector.js:22:31)
    at DataCollector.addErrorForUrl (/usr/src/app/lib/plugins/html/dataCollector.js:94:10)
    at Object.processMessage (/usr/src/app/lib/plugins/html/index.js:58:27)
    at /usr/src/app/lib/core/queueHandler.js:214:32
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at processImmediate (internal/timers.js:464:21)
[2021-07-13 08:56:19] INFO: HTML stored in /sitespeed.io/sitespeed-result/sitespeedScript_js/2021-07-13-08-56-04
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myApp@8.1.6 test:sitespeed: `docker run --shm-size 2g --rm -v "$(pwd):/sitespeed.io" --network=host sitespeedio/sitespeed.io:17.8.3 ./test/performance/sitespeedScript.js --multi -n 1 --html.summaryBoxes -b chrome`
npm ERR! Exit status 1
```

I did get it working by replacing byJsAndWait with:
```
  await commands.js.run(`
    document.querySelector('[data-test-id="myTestId"]').querySelector("a").click();
  `);
```

**Comment by soulgalore** [comment]
Hi @ledleds thank you for creating the issue! I think the documentation is missing parts here and the code also be smarter, let me create an issue for fixing that for the coming release. At the moment the backend code append `.click` to the code that you pass in (but the documentation talks about evaluating the expression). Passing on` document.querySelector('[data-test-id="myTestId"]').querySelector("a")` should work in your case. Let me fix the documentation (by adding an example and then also make the code smarter for the next release). Thanks again for creating the issue!

**Comment by ledleds** [comment]
Awesome! Thanks for the super quick response, and for Sitespeed! 🎉 
Would you like me to close this for now?

**Comment by soulgalore** [comment]
No, lets keep this open until I've done some changes in Browsertime so it can handle expressions that ends with a ;-mark.

**Comment by soulgalore** [comment]
I've released a new version with a fix and the updated sitespeed.io just got released too.

**Comment by ledleds** [comment]
Thanks @soulgalore!
