### ISSUE TITLE
sitespeed -vv failed on browsertime

### ISSUE THREAD

**Issue by mypchas6fans** [sitespeedio/browsertime#1639]
I tried to run below command:

`docker run sitespeedio/sitespeed.io:19.4.2 -vv -b chrome --outputFolder result --graphite.host MYHOST --graphite.auth USER:PWD --graphite.addSlugToKey true --slug firstView --graphite.namespace sitespeed_io.desktop MYURL`

It prompted below message and the command completed as failure:

`[2021-09-16 09:28:14] DEBUG: [browsertime.command.measure] Mark run as failure with message Cannot read property 'log' of undefined
[2021-09-16 09:28:14] ERROR: [browsertime] TypeError: Cannot read property 'log' of undefined
    at Chromium.afterEachURL (/usr/src/app/node_modules/browsertime/lib/chrome/webdriver/chromium.js:295:53)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Measure.collect (/usr/src/app/node_modules/browsertime/lib/core/engine/command/measure.js:503:5)
    at async /usr/src/app/node_modules/browsertime/lib/core/engine/run.js:9:9
    at async Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:214:9)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:277:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:151:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:150:26)`

When I add --browsertime.skipHar it goes fine.

**Comment by soulgalore** [comment]
Hi @mypchas6fans thanks again for reporting! This is fixed in sitespeed.io 19.5.0.

**Comment by mypchas6fans** [comment]
@soulgalore Thank you! Verified on 19.5.0 successfully.
