### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#168]
On our test server we test a couple of URLs that are failing and after that we get:
<pre>
2016-07-13 13:00:19] Start tsproxy:/usr/lib/node_modules/sitespeed.io/node_modu
les/browsertime/vendor/tsproxy.py --rtt 28 --inkbps 5000 --outkbps 1000
[2016-07-13 13:00:19] Error: spawn ENOMEM
    at exports._errnoException (util.js:873:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
</pre>

The error that happens before looks like:
<pre>
[2016-07-13 12:14:24] http://www.hoppla.com generated the following error
 in Browsertime UrlLoadError: Failed to load http://www.hoppla.com
    at BrowsertimeError (/usr/lib/node_modules/sitespeed.io/node_modules/browser
time/lib/support/errors.js:5:10)
</pre>

Do we run the stop method (that closes the proxy) if we get an error?

**Comment by soulgalore** [comment]
I tested it locally and it seems to be ok.

**Comment by soulgalore** [comment]
Haven't been able to reproduce, close this for now.
