### ISSUE TITLE
visualmetrics-portable hero time error

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#1753]
I picked up one error on the test server from the new portable script:

```
09:48:36.736 - '<' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/usr/src/app/node_modules/browsertime/browsertime/visualmetrics-portable.py", line 2707, in main
    metrics = calculate_visual_metrics(
  File "/usr/src/app/node_modules/browsertime/browsertime/visualmetrics-portable.py", line 1957, in calculate_visual_metrics
    hero_timings_sorted = sorted(
TypeError: '<' not supported between instances of 'NoneType' and 'int'

```

I'll try to get a video for that tonight.

**Comment by gmierz** [comment]
Thanks for finding this! I'll take a look once I have the video and visual elements that caused this.

**Comment by soulgalore** [comment]
I couldn't reproduce this locally and looking at the test result it wasn't uploaded, so probably something was fundamental broken when we tried to record the video. Gonna close it now and then create a new one if it happens again. One thing that would be cool that we could implement is that we keep the original video if visual metrics fails, so its easy to try locally.

**Comment by gmierz** [comment]
+1 to keeping the original video that failed, that's a good idea

**Comment by soulgalore** [comment]
It's the same page again but a different error:

```
15:26:12.059 - tile cannot extend outside image
Traceback (most recent call last):
  File "/usr/src/app/node_modules/browsertime/browsertime/visualmetrics-portable.py", line 111, in crop_im
    return Image.fromarray(
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 2834, in fromarray
    return frombuffer(mode, size, obj, "raw", rawmode, 0, 1)
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 2761, in frombuffer
    return frombytes(mode, size, data, decoder_name, args)
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 2707, in frombytes
    im.frombytes(data, decoder_name, args)
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 780, in frombytes
    d.setimage(self.im)
ValueError: tile cannot extend outside image
```

I'll push so we store the original video and keep this open until we have video we can work with.

**Comment by gmierz** [comment]
Sounds good, I think that either the image or the crop region being given is empty. Can you get the visual element positions too? I had a visualElements file last time I tested it

**Comment by soulgalore** [comment]
`You are right, let me fix that the coming days.

**Comment by soulgalore** [comment]
Hi @gmierz so I finally got hold of one of the examples where they fail on the test server:

[2-visualElements copy.json.gz](https://github.com/sitespeedio/browsertime/files/8484523/2-visualElements.copy.json.gz)

https://user-images.githubusercontent.com/540757/163266417-2358eb58-121c-40e1-8e2f-1a38f97d7c7a.mp4

I haven't tried them myself yet.

**Comment by soulgalore** [comment]
I tried and it's reproducible.

**Comment by gmierz** [comment]
@soulgalore the issue should be fixed now with this merged PR: https://github.com/sitespeedio/browsertime/pull/1770

I'll close this now, and we can re-open it if we see it again.
