### ISSUE TITLE
Chrome not reachable

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#178]
Got a couple of these when running in Docker:

<pre>
[2016-08-17 04:10:13] WebDriverError:WebDriverError: chrome not reachable
  (Session info: chrome=52.0.2743.116)
  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 3.13.0-85-generic x86_64)
[2016-08-17 04:10:13] Could not load URLUrlLoadError: Failed to load http://reseguiden.se, cause: chrome not reachable
  (Session info: chrome=52.0.2743.116)
  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 3.13.0-85-generic x86_64)
[2016-08-17 04:10:13] http://hepp.se generated the following error in Browsertime UrlLoadError: Failed to load http://hepp.se
</pre>

I wonder if we could catch them and retry?

**Comment by soulgalore** [comment]
We catch it and then rertry but get the same error again. The Chromedriver log looks like this:
<pre>
178.045][INFO]: COMMAND Navigate {
   "url": "http://liseberg.se"
}
[178.045][INFO]: Waiting for pending navigations...
[178.049][INFO]: Done waiting for pending navigations. Status: ok
[178.066][INFO]: Waiting for pending navigations...
[185.020][SEVERE]: Unable to receive message from renderer
[185.020][INFO]: Done waiting for pending navigations. Status: disconnected: Unable to receive message from renderer
[185.022][INFO]: RESPONSE Navigate
[185.038][INFO]: COMMAND ExecuteScript {
   "args": [  ],
   "script": "return document.documentURI;"
}
[185.038][INFO]: resolved localhost to ["::1","127.0.0.1"]
[185.044][INFO]: RESPONSE ExecuteScript chrome not reachable
  (Session info: chrome=52.0.2743.116)
[185.116][INFO]: COMMAND Navigate {
   "url": "http://liseberg.se"
}
[185.116][INFO]: resolved localhost to ["::1","127.0.0.1"]
[185.117][INFO]: RESPONSE Navigate chrome not reachable
  (Session info: chrome=52.0.2743.116)
[185.169][INFO]: COMMAND Quit {
}
[185.170][INFO]: RESPONSE Quit
[185.313][INFO]: COMMAND InitSession {
   "desiredCapabilities": {
      "browserName": "chrome",
      "chromeOptions": {
         "args": [ "--disable-plugins-discovery", "--disable-bundled-ppapi-flash", "--enable-experimental-extension-apis", "--disable-back\
ground-networking", "--no-default-browser-check", "--no-first-run", "--process-per-tab", "--new-window", "--disable-translate", "--disable\
-desktop-notifications", "--allow-running-insecure-content", "--disable-save-password-bubble", "--disable-component-update", "--disable-ba\
ckground-downloads", "--disable-add-to-shelf", "--disable-client-side-phishing-detection", "--disable-datasaver-prompt", "--disable-defaul\
t-apps", "--disable-domain-reliability", "..." ],
         "perfLoggingPrefs": {
            "enableNetwork": true,
            "enablePage": true
         }
      },
      "loggingPrefs": {
         "performance": "INFO"
      }
   }
}
</pre>

**Comment by soulgalore** [comment]
We still get this, but it seems tied to specific URLs.
<pre>
[2016-09-04 06:05:18] Catched a WebDriverError [chrome not reachable
  (Session info: chrome=52.0.2743.116)
  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 4.4.0-34-generic x
86_64)]. Try one more time.WebDriverError: chrome not reachable
  (Session info: chrome=52.0.2743.116)
  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 4.4.0-34-generic x
86_64)
[2016-09-04 06:05:19] WebDriverError:WebDriverError: chrome not reachable
  (Session info: chrome=52.0.2743.116)
  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 4.4.0-34-generic x
86_64)
[2016-09-04 06:05:19] Could not load URLUrlLoadError: Failed to load http://www.cnet.com/, cause: chrome not reachabl
e
  (Session info: chrome=52.0.2743.116)
  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 4.4.0-34-generic x
86_64)
[2016-09-04 06:05:19] http://www.cnet.com/ generated the following error in Browsertime UrlLoadError: Failed to load 
http://www.cnet.com/
    at BrowsertimeError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:5:5)
    at UrlLoadError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:19:5)
    at getUrl.then.then.catch.catch (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:147:15)
    at tryCatcher (/usr/src/app/node_modules/browsertime/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/browsertime/node_modules/bluebird/js/release/prom
ise.js:510:31)
</pre>

**Comment by beenanner** [comment]
@soulgalore looks like this may be coming from 302 redirects? Reproducible with http://liseberg.se and  http://cnet.com, but not https://cnet.com/ (301)

**Comment by soulgalore** [comment]
I think the last things now with Chrome to run stable in Docker (see the changes in start.sh).
