### ISSUE TITLE
Errors in visual metrics portable script

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#1808]
There's been some errors in the logs from the visual metrics-portable script the last days, let me document them and follow up.

```
18:24:01.532 - Extracting frames from /sitespeed.io/sitespeed-result/alexa/2022-06-13-18-12-40/pages/xw_qq_com/data/video/3.mp4 to /sitespeed.io/sitespeed-result/alexa/2022-06-13-18-12-40/pages/xw_qq_com/data/filmstrip/3
18:24:07.914 - Cropped image is empty. Image dimensions: (600, 385, 3), Crop Region: 201, 73, 27, 635
Traceback (most recent call last):
  File "/usr/src/app/node_modules/browsertime/browsertime/visualmetrics-portable.py", line 114, in crop_im
    raise Exception(
Exception: Cropped image is empty. Image dimensions: (600, 385, 3), Crop Region: 201, 73, 27, 635
18:24:07.914 - 'NoneType' object has no attribute 'save'
Traceback (most recent call last):
  File "/usr/src/app/node_modules/browsertime/browsertime/visualmetrics-portable.py", line 1549, in calculate_hero_time
    target_mask.save(target_mask_path)
AttributeError: 'NoneType' object has no attribute 'save'
18:24:07.914 - '<' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/usr/src/app/node_modules/browsertime/browsertime/visualmetrics-portable.py", line 1914, in main
    metrics = calculate_visual_metrics(
  File "/usr/src/app/node_modules/browsertime/browsertime/visualmetrics-portable.py", line 1277, in calculate_visual_metrics
    hero_timings_sorted = sorted(
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

```
[2022-06-13 01:41:42] ERROR: Log from VisualMetrics: 01:41:40.507 - Processing frames from video /sitespeed.io/sitespeed-result/alexa/2022-06-13-01-40-16/pages/www_google_com/data/video/3.mp4 to /sitespeed.io/sitespeed-result/alexa/2022-06-13-01-40-16/pages/www_google_com/data/filmstrip/3
01:41:40.570 - Extracting frames from /sitespeed.io/sitespeed-result/alexa/2022-06-13-01-40-16/pages/www_google_com/data/video/3.mp4 to /sitespeed.io/sitespeed-result/alexa/2022-06-13-01-40-16/pages/www_google_com/data/filmstrip/3
01:41:42.295 - Cropped image is empty. Image dimensions: (600, 385, 3), Crop Region: 291, 42, 75, 610
Traceback (most recent call last):
  File "/usr/src/app/node_modules/browsertime/browsertime/visualmetrics-portable.py", line 114, in crop_im
    raise Exception(
Exception: Cropped image is empty. Image dimensions: (600, 385, 3), Crop Region: 291, 42, 75, 610
01:41:42.295 - 'NoneType' object has no attribute 'save'
Traceback (most recent call last):
  File "/usr/src/app/node_modules/browsertime/browsertime/visualmetrics-portable.py", line 1549, in calculate_hero_time
    target_mask.save(target_mask_path)
AttributeError: 'NoneType' object has no attribute 'save'
01:41:42.295 - '<' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/usr/src/app/node_modules/browsertime/browsertime/visualmetrics-portable.py", line 1914, in main
    metrics = calculate_visual_metrics(
  File "/usr/src/app/node_modules/browsertime/browsertime/visualmetrics-portable.py", line 1277, in calculate_visual_metrics
    hero_timings_sorted = sorted(
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**Comment by soulgalore** [comment]
@gmierz so I forgot what `Cropped image is empty. Image dimensions ...`? I't one of the "hero"-element that fails right and I guess the largest contentful paint since that was the last one I added, and I said I should fix that by verify that it existed? I think I did but not good enough. I'll check that again the coming days.

**Comment by gmierz** [comment]
Yes, this is coming from the hero elements so there's something wrong with the sizes/dimensions we're getting from them. Verifying the element exists or has a non-zero size would be a good way of taking care of this issue.

**Comment by soulgalore** [comment]
This is fixed, the problem was that if one fails, all fails.
