### ISSUE TITLE
Error while installing v1.0.0-beta.6

### ISSUE THREAD

**Issue by usherfu** [sitespeedio/browsertime#193]
Hi,
I am getting following error when trying to install v1.0 beta6
   npm install -g browsertime@v1.0.0-beta.6

> alto-saxophone@2.24.0 install /usr/local/lib/node_modules/browsertime/node_modules/alto-saxophone
> node install.js

/usr/local/lib/node_modules/browsertime/node_modules/alto-saxophone/install.js:28
        throw err;
        ^
RequestError: tunneling socket could not be established, cause=Parse Error
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/browsertime/node_modules/alto-saxophone/node_modules/download/nod
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at ClientRequest.onError (/usr/local/lib/node_modules/browsertime/node_modules/alto-saxophone/node_modules/download/node_mo
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketOnData (_http_client.js:325:9)
    at emitOne (events.js:77:13)
npm info postinstall soprano-saxophone@0.10.0
npm info alto-saxophone@2.24.0 Failed to exec install script
npm ERR! Linux 4.4.12-boot2docker
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "browsertime@v1.0.0-beta.6"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! alto-saxophone@2.24.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alto-saxophone@2.24.0 install script 'node install.js'.
npm ERR! This is most likely a problem with the alto-saxophone package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alto-saxophone
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls alto-saxophone
npm ERR! There is likely additional logging output above.
npm info preuninstall alto-saxophone@2.24.0
npm info uninstall alto-saxophone@2.24.0
npm info postuninstall alto-saxophone@2.24.0
npm info preuninstall browsertime@1.0.0-beta.6
npm info uninstall browsertime@1.0.0-beta.6
npm info postuninstall browsertime@1.0.0-beta.6

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/testautomation/PerfDocker/browser-perf/npm-debug.log

Is this error related to browsertime or alto-saxophone?  Anyone run into this error before?  Thanks!

**Comment by soulgalore** [comment]
It looks like a temporary npm glitch, can you try to do it again? I tried now on my mac and it worked.

**Comment by usherfu** [comment]
Hi,
I tried again this morning several times, the error seems to have changed slightly, but still run into issue while installing alto-saxophone.  

```
npm info alto-saxophone@2.24.0 Failed to exec install script

> soprano-saxophone@0.10.0 install /usr/local/lib/node_modules/browsertime/node_modules/soprano-saxophone
> node install.js

     fetch : https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-linux64.tar.gz
  progress : [====================] 100% 0.0s

npm info postinstall soprano-saxophone@0.10.0
npm ERR! Linux 4.4.12-boot2docker
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "browsertime@v1.0.0-beta.6"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! alto-saxophone@2.24.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alto-saxophone@2.24.0 install script 'node install.js'.
npm ERR! This is most likely a problem with the alto-saxophone package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alto-saxophone
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls alto-saxophone
npm ERR! There is likely additional logging output above.
npm info preuninstall alto-saxophone@2.24.0
npm info uninstall alto-saxophone@2.24.0
npm info postuninstall alto-saxophone@2.24.0
npm info preuninstall browsertime@1.0.0-beta.6
npm info uninstall browsertime@1.0.0-beta.6
npm info postuninstall browsertime@1.0.0-beta.6

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/testautomation/npm-debug.log

```

Note that I was able to install browsertime (0.12.3) with the latest tag.  Is it a problem with alto-saxophone?  Thanks!

**Comment by beenanner** [comment]
@usherfu  just tested appears to be working fine with the latest version.

```
➜  ~ npm install -g browsertime@v1.0.0-beta.9
/home/beenanner/.nvm/versions/node/v6.9.1/bin/browsertime -> /home/beenanner/.nvm/versions/node/v6.9.1/lib/node_modules/browsertime/bin/browsertime.js

> alto-saxophone@2.24.0 install /home/beenanner/.nvm/versions/node/v6.9.1/lib/node_modules/browsertime/node_modules/alto-saxophone
> node install.js

     fetch : http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  progress : [====================] 100% 0.0s


> soprano-saxophone@0.10.0 install /home/beenanner/.nvm/versions/node/v6.9.1/lib/node_modules/browsertime/node_modules/soprano-saxophone
> node install.js

     fetch : https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-linux64.tar.gz
  progress : [====================] 100% 0.0s

/home/beenanner/.nvm/versions/node/v6.9.1/lib
└─┬ browsertime@1.0.0-beta.9 
  ├─┬ alto-saxophone@2.24.0 
  │ ├─┬ download@4.4.3 
  │ │ ├─┬ caw@1.2.0 
  │ │ │ ├─┬ get-proxy@1.1.0 
  │ │ │ │ └─┬ rc@1.1.6 
  │ │ │ │   ├── deep-extend@0.4.1 
  │ │ │ │   ├── ini@1.3.4 
  │ │ │ │   └── strip-json-comments@1.0.4 
  │ │ │ ├── is-obj@1.0.1 
  │ │ │ ├── object-assign@3.0.0 
  │ │ │ └── tunnel-agent@0.4.3 
  │ │ ├─┬ concat-stream@1.5.2 
  │ │ │ ├── inherits@2.0.3 
  │ │ │ ├── readable-stream@2.0.6 
  │ │ │ └── typedarray@0.0.6 
  │ │ ├─┬ each-async@1.1.1 
  │ │ │ ├── onetime@1.1.0 
  │ │ │ └── set-immediate-shim@1.0.1 
  │ │ ├─┬ filenamify@1.2.1 
  │ │ │ ├── filename-reserved-regex@1.0.0 
  │ │ │ ├── strip-outer@1.0.0 
  │ │ │ └── trim-repeated@1.0.0 
  │ │ ├─┬ got@5.7.1 
  │ │ │ ├─┬ create-error-class@3.0.2 
  │ │ │ │ └── capture-stack-trace@1.0.0 
  │ │ │ ├── duplexer2@0.1.4 
  │ │ │ ├── is-redirect@1.0.0 
  │ │ │ ├── is-retry-allowed@1.1.0 
  │ │ │ ├── lowercase-keys@1.0.0 
  │ │ │ ├── node-status-codes@1.0.0 
  │ │ │ ├─┬ parse-json@2.2.0 
  │ │ │ │ └─┬ error-ex@1.3.0 
  │ │ │ │   └── is-arrayish@0.2.1 
  │ │ │ ├─┬ pinkie-promise@2.0.1 
  │ │ │ │ └── pinkie@2.0.4 
  │ │ │ ├── timed-out@3.0.0 
  │ │ │ ├── unzip-response@1.0.2 
  │ │ │ └─┬ url-parse-lax@1.0.0 
  │ │ │   └── prepend-http@1.0.4 
  │ │ ├─┬ gulp-decompress@1.2.0 
  │ │ │ ├─┬ archive-type@3.2.0 
  │ │ │ │ └── file-type@3.9.0 
  │ │ │ ├─┬ decompress@3.0.0 
  │ │ │ │ ├─┬ buffer-to-vinyl@1.1.0 
  │ │ │ │ │ └── uuid@2.0.3 
  │ │ │ │ ├─┬ decompress-tar@3.1.0 
  │ │ │ │ │ ├── is-tar@1.0.0 
  │ │ │ │ │ ├── object-assign@2.1.1 
  │ │ │ │ │ ├─┬ strip-dirs@1.1.1 
  │ │ │ │ │ │ ├─┬ is-absolute@0.1.7 
  │ │ │ │ │ │ │ └── is-relative@0.1.3 
  │ │ │ │ │ │ ├── is-natural-number@2.1.1 
  │ │ │ │ │ │ └── sum-up@1.0.3 
  │ │ │ │ │ ├─┬ tar-stream@1.5.2 
  │ │ │ │ │ │ ├─┬ bl@1.1.2 
  │ │ │ │ │ │ │ └── readable-stream@2.0.6 
  │ │ │ │ │ │ └── end-of-stream@1.1.0 
  │ │ │ │ │ └─┬ vinyl@0.4.6 
  │ │ │ │ │   └── clone@0.2.0 
  │ │ │ │ ├─┬ decompress-tarbz2@3.1.0 
  │ │ │ │ │ ├── is-bzip2@1.0.0 
  │ │ │ │ │ ├── object-assign@2.1.1 
  │ │ │ │ │ ├─┬ seek-bzip@1.0.5 
  │ │ │ │ │ │ └─┬ commander@2.8.1 
  │ │ │ │ │ │   └── graceful-readlink@1.0.1 
  │ │ │ │ │ └─┬ vinyl@0.4.6 
  │ │ │ │ │   └── clone@0.2.0 
  │ │ │ │ ├─┬ decompress-targz@3.1.0 
  │ │ │ │ │ ├── is-gzip@1.0.0 
  │ │ │ │ │ ├── object-assign@2.1.1 
  │ │ │ │ │ └─┬ vinyl@0.4.6 
  │ │ │ │ │   └── clone@0.2.0 
  │ │ │ │ ├─┬ decompress-unzip@3.4.0 
  │ │ │ │ │ ├── is-zip@1.0.0 
  │ │ │ │ │ ├── stat-mode@0.2.2 
  │ │ │ │ │ ├─┬ through2@2.0.1 
  │ │ │ │ │ │ └── readable-stream@2.0.6 
  │ │ │ │ │ └─┬ yauzl@2.7.0 
  │ │ │ │ │   ├── buffer-crc32@0.2.5 
  │ │ │ │ │   └─┬ fd-slicer@1.0.1 
  │ │ │ │ │     └── pend@1.2.0 
  │ │ │ │ └── vinyl-assign@1.2.1 
  │ │ │ └─┬ gulp-util@3.0.7 
  │ │ │   ├── array-differ@1.0.0 
  │ │ │   ├── array-uniq@1.0.3 
  │ │ │   ├── beeper@1.1.0 
  │ │ │   ├── dateformat@1.0.12 
  │ │ │   ├─┬ fancy-log@1.2.0 
  │ │ │   │ └── time-stamp@1.0.1 
  │ │ │   ├─┬ gulplog@1.0.0 
  │ │ │   │ └── glogg@1.0.0 
  │ │ │   ├─┬ has-gulplog@0.1.0 
  │ │ │   │ └── sparkles@1.0.0 
  │ │ │   ├── lodash._reescape@3.0.0 
  │ │ │   ├── lodash._reevaluate@3.0.0 
  │ │ │   ├── lodash._reinterpolate@3.0.0 
  │ │ │   ├─┬ lodash.template@3.6.2 
  │ │ │   │ ├── lodash._basecopy@3.0.1 
  │ │ │   │ ├── lodash._basetostring@3.0.1 
  │ │ │   │ ├── lodash._basevalues@3.0.0 
  │ │ │   │ ├── lodash._isiterateecall@3.0.9 
  │ │ │   │ ├─┬ lodash.escape@3.2.0 
  │ │ │   │ │ └── lodash._root@3.0.1 
  │ │ │   │ ├─┬ lodash.keys@3.1.2 
  │ │ │   │ │ ├── lodash._getnative@3.9.1 
  │ │ │   │ │ ├── lodash.isarguments@3.1.0 
  │ │ │   │ │ └── lodash.isarray@3.0.4 
  │ │ │   │ ├── lodash.restparam@3.6.1 
  │ │ │   │ └── lodash.templatesettings@3.1.1 
  │ │ │   ├─┬ multipipe@0.1.2 
  │ │ │   │ └─┬ duplexer2@0.0.2 
  │ │ │   │   └─┬ readable-stream@1.1.14 
  │ │ │   │     └── isarray@0.0.1 
  │ │ │   ├── object-assign@3.0.0 
  │ │ │   ├─┬ through2@2.0.1 
  │ │ │   │ └── readable-stream@2.0.6 
  │ │ │   └── vinyl@0.5.3 
  │ │ ├── gulp-rename@1.2.2 
  │ │ ├── is-url@1.2.2 
  │ │ ├── read-all-stream@3.1.0 
  │ │ ├─┬ readable-stream@2.1.5 
  │ │ │ ├── buffer-shims@1.0.0 
  │ │ │ ├── core-util-is@1.0.2 
  │ │ │ ├── isarray@1.0.0 
  │ │ │ ├── process-nextick-args@1.0.7 
  │ │ │ ├── string_decoder@0.10.31 
  │ │ │ └── util-deprecate@1.0.2 
  │ │ ├── stream-combiner2@1.1.1 
  │ │ ├─┬ vinyl@1.2.0 
  │ │ │ ├── clone@1.0.2 
  │ │ │ ├── clone-stats@0.0.1 
  │ │ │ └── replace-ext@0.0.1 
  │ │ ├─┬ vinyl-fs@2.4.4 
  │ │ │ ├─┬ duplexify@3.5.0 
  │ │ │ │ ├── end-of-stream@1.0.0 
  │ │ │ │ └── stream-shift@1.0.0 
  │ │ │ ├─┬ glob-stream@5.3.5 
  │ │ │ │ ├── extend@3.0.0 
  │ │ │ │ ├── glob@5.0.15 
  │ │ │ │ ├─┬ glob-parent@3.0.1 
  │ │ │ │ │ ├─┬ is-glob@3.1.0 
  │ │ │ │ │ │ └── is-extglob@2.1.0 
  │ │ │ │ │ └── path-dirname@1.0.2 
  │ │ │ │ ├─┬ micromatch@2.3.11 
  │ │ │ │ │ ├─┬ arr-diff@2.0.0 
  │ │ │ │ │ │ └── arr-flatten@1.0.1 
  │ │ │ │ │ ├── array-unique@0.2.1 
  │ │ │ │ │ ├─┬ braces@1.8.5 
  │ │ │ │ │ │ ├─┬ expand-range@1.8.2 
  │ │ │ │ │ │ │ └─┬ fill-range@2.2.3 
  │ │ │ │ │ │ │   ├── is-number@2.1.0 
  │ │ │ │ │ │ │   ├── isobject@2.1.0 
  │ │ │ │ │ │ │   ├── randomatic@1.1.5 
  │ │ │ │ │ │ │   └── repeat-string@1.6.1 
  │ │ │ │ │ │ ├── preserve@0.2.0 
  │ │ │ │ │ │ └── repeat-element@1.1.2 
  │ │ │ │ │ ├─┬ expand-brackets@0.1.5 
  │ │ │ │ │ │ └── is-posix-bracket@0.1.1 
  │ │ │ │ │ ├─┬ extglob@0.3.2 
  │ │ │ │ │ │ └── is-extglob@1.0.0 
  │ │ │ │ │ ├── filename-regex@2.0.0 
  │ │ │ │ │ ├── is-extglob@1.0.0 
  │ │ │ │ │ ├── is-glob@2.0.1 
  │ │ │ │ │ ├─┬ kind-of@3.0.4 
  │ │ │ │ │ │ └── is-buffer@1.1.4 
  │ │ │ │ │ ├── normalize-path@2.0.1 
  │ │ │ │ │ ├─┬ object.omit@2.0.1 
  │ │ │ │ │ │ ├─┬ for-own@0.1.4 
  │ │ │ │ │ │ │ └── for-in@0.1.6 
  │ │ │ │ │ │ └── is-extendable@0.1.1 
  │ │ │ │ │ ├─┬ parse-glob@3.0.4 
  │ │ │ │ │ │ ├─┬ glob-base@0.3.0 
  │ │ │ │ │ │ │ ├── glob-parent@2.0.0 
  │ │ │ │ │ │ │ └─┬ is-glob@2.0.1 
  │ │ │ │ │ │ │   └── is-extglob@1.0.0 
  │ │ │ │ │ │ ├── is-dotfile@1.0.2 
  │ │ │ │ │ │ ├── is-extglob@1.0.0 
  │ │ │ │ │ │ └── is-glob@2.0.1 
  │ │ │ │ │ └─┬ regex-cache@0.4.3 
  │ │ │ │ │   ├── is-equal-shallow@0.1.3 
  │ │ │ │ │   └── is-primitive@2.0.0 
  │ │ │ │ ├── ordered-read-streams@0.3.0 
  │ │ │ │ ├─┬ through2@0.6.5 
  │ │ │ │ │ └─┬ readable-stream@1.0.34 
  │ │ │ │ │   └── isarray@0.0.1 
  │ │ │ │ ├─┬ to-absolute-glob@0.1.1 
  │ │ │ │ │ └── extend-shallow@2.0.1 
  │ │ │ │ └─┬ unique-stream@2.2.1 
  │ │ │ │   └─┬ json-stable-stringify@1.0.1 
  │ │ │ │     └── jsonify@0.0.0 
  │ │ │ ├── graceful-fs@4.1.10 
  │ │ │ ├─┬ gulp-sourcemaps@1.6.0 
  │ │ │ │ ├── convert-source-map@1.3.0 
  │ │ │ │ └─┬ through2@2.0.1 
  │ │ │ │   └── readable-stream@2.0.6 
  │ │ │ ├── is-valid-glob@0.3.0 
  │ │ │ ├── lazystream@1.0.0 
  │ │ │ ├── lodash.isequal@4.4.0 
  │ │ │ ├── merge-stream@1.0.0 
  │ │ │ ├─┬ strip-bom@2.0.0 
  │ │ │ │ └── is-utf8@0.2.1 
  │ │ │ ├─┬ strip-bom-stream@1.0.0 
  │ │ │ │ └── first-chunk-stream@1.0.0 
  │ │ │ ├─┬ through2@2.0.1 
  │ │ │ │ └── readable-stream@2.0.6 
  │ │ │ ├─┬ through2-filter@2.0.0 
  │ │ │ │ ├─┬ through2@2.0.1 
  │ │ │ │ │ └── readable-stream@2.0.6 
  │ │ │ │ └── xtend@4.0.1 
  │ │ │ └── vali-date@1.0.0 
  │ │ └─┬ ware@1.3.0 
  │ │   └─┬ wrap-fn@0.1.5 
  │ │     └── co@3.1.0 
  │ └─┬ download-status@2.2.1 
  │   ├─┬ chalk@0.5.1 
  │   │ ├── ansi-styles@1.1.0 
  │   │ ├─┬ has-ansi@0.1.0 
  │   │ │ └── ansi-regex@0.2.1 
  │   │ ├── strip-ansi@0.3.0 
  │   │ └── supports-color@0.2.0 
  │   ├─┬ lpad-align@1.1.0 
  │   │ ├── get-stdin@4.0.1 
  │   │ ├── longest@1.0.1 
  │   │ ├── lpad@2.0.1 
  │   │ └─┬ meow@3.7.0 
  │   │   ├─┬ camelcase-keys@2.1.0 
  │   │   │ └── camelcase@2.1.1 
  │   │   ├─┬ loud-rejection@1.6.0 
  │   │   │ ├─┬ currently-unhandled@0.4.1 
  │   │   │ │ └── array-find-index@1.0.2 
  │   │   │ └── signal-exit@3.0.1 
  │   │   ├── map-obj@1.0.1 
  │   │   ├─┬ redent@1.0.0 
  │   │   │ ├─┬ indent-string@2.1.0 
  │   │   │ │ └─┬ repeating@2.0.1 
  │   │   │ │   └── is-finite@1.0.2 
  │   │   │ └── strip-indent@1.0.1 
  │   │   └── trim-newlines@1.0.0 
  │   ├── object-assign@2.1.1 
  │   └── progress@1.1.8 
  ├── bluebird@3.4.6 
  ├─┬ execa@0.4.0 
  │ ├─┬ cross-spawn-async@2.2.5 
  │ │ ├─┬ lru-cache@4.0.1 
  │ │ │ ├── pseudomap@1.0.2 
  │ │ │ └── yallist@2.0.0 
  │ │ └─┬ which@1.2.11 
  │ │   └── isexe@1.1.2 
  │ ├── is-stream@1.1.0 
  │ ├── npm-run-path@1.0.0 
  │ ├── object-assign@4.1.0 
  │ ├── path-key@1.0.0 
  │ └── strip-eof@1.0.0 
  ├── fast-stats@0.0.3 
  ├─┬ hasbin@1.2.3 
  │ └── async@1.5.2 
  ├─┬ intel@1.1.1 
  │ ├─┬ chalk@1.1.3 
  │ │ ├── ansi-styles@2.2.1 
  │ │ ├── escape-string-regexp@1.0.5 
  │ │ ├─┬ has-ansi@2.0.0 
  │ │ │ └── ansi-regex@2.0.0 
  │ │ ├── strip-ansi@3.0.1 
  │ │ └── supports-color@2.0.0 
  │ ├── dbug@0.4.2 
  │ ├── stack-trace@0.0.9 
  │ ├── strftime@0.9.2 
  │ ├── symbol@0.3.0 
  │ └── utcstring@0.1.0 
  ├── lodash.foreach@4.5.0 
  ├── lodash.get@4.4.2 
  ├── lodash.groupby@4.6.0 
  ├── lodash.isempty@4.4.0 
  ├── lodash.merge@4.6.0 
  ├── lodash.pick@4.4.0 
  ├── lodash.set@4.3.2 
  ├─┬ mkdirp@0.5.1 
  │ └── minimist@0.0.8 
  ├── moment@2.15.0 
  ├─┬ selenium-webdriver@3.0.0-beta-3 
  │ ├── adm-zip@0.4.4 
  │ ├─┬ rimraf@2.5.4 
  │ │ └─┬ glob@7.1.1 
  │ │   ├── fs.realpath@1.0.0 
  │ │   ├─┬ inflight@1.0.6 
  │ │   │ └── wrappy@1.0.2 
  │ │   ├─┬ minimatch@3.0.3 
  │ │   │ └─┬ brace-expansion@1.1.6 
  │ │   │   ├── balanced-match@0.4.2 
  │ │   │   └── concat-map@0.0.1 
  │ │   ├── once@1.3.3 
  │ │   └── path-is-absolute@1.0.1 
  │ ├── tmp@0.0.24 
  │ ├─┬ ws@1.1.1 
  │ │ ├── options@0.0.6 
  │ │ └── ultron@1.0.2 
  │ └─┬ xml2js@0.4.4 
  │   ├── sax@0.6.1 
  │   └── xmlbuilder@8.2.2 
  ├─┬ sltc@0.5.0 
  │ ├── hasbin@1.2.2 
  │ └── minimist@1.2.0 
  ├── soprano-saxophone@0.10.0 
  ├── tough-cookie@2.3.1 
  ├── valid-url@1.0.9 
  └─┬ yargs@5.0.0 
    ├─┬ cliui@3.2.0 
    │ └── wrap-ansi@2.0.0 
    ├── decamelize@1.2.0 
    ├── get-caller-file@1.0.2 
    ├── lodash.assign@4.2.0 
    ├─┬ os-locale@1.4.0 
    │ └─┬ lcid@1.0.0 
    │   └── invert-kv@1.0.0 
    ├─┬ read-pkg-up@1.0.1 
    │ ├─┬ find-up@1.1.2 
    │ │ └── path-exists@2.1.0 
    │ └─┬ read-pkg@1.1.0 
    │   ├─┬ load-json-file@1.1.0 
    │   │ └── pify@2.3.0 
    │   ├─┬ normalize-package-data@2.3.5 
    │   │ ├── hosted-git-info@2.1.5 
    │   │ ├─┬ is-builtin-module@1.0.0 
    │   │ │ └── builtin-modules@1.1.1 
    │   │ ├── semver@5.3.0 
    │   │ └─┬ validate-npm-package-license@3.0.1 
    │   │   ├─┬ spdx-correct@1.0.2 
    │   │   │ └── spdx-license-ids@1.2.2 
    │   │   └── spdx-expression-parse@1.0.4 
    │   └── path-type@1.1.0 
    ├── require-directory@2.1.1 
    ├── require-main-filename@1.0.1 
    ├── set-blocking@2.0.0 
    ├─┬ string-width@1.0.2 
    │ ├── code-point-at@1.1.0 
    │ └─┬ is-fullwidth-code-point@1.0.0 
    │   └── number-is-nan@1.0.1 
    ├── which-module@1.0.0 
    ├── window-size@0.2.0 
    ├── y18n@3.2.1 
    └─┬ yargs-parser@3.2.0 
      └── camelcase@3.0.0 


```
