### ISSUE TITLE
BrowserError: session not created exception (Chrome)

### ISSUE THREAD

**Issue by fhemberger** [sitespeedio/browsertime#223]
I can't measure sites with a fresh install of sitespeed.io in Chrome. I used the example from the documentation, but it's the same error regardless the site tested.

```
sitespeed.io https://en.wikipedia.org/wiki/Barack_Obama --browser chrome
[2016-11-19 13:16:41] Versions OS: darwin 15.6.0 nodejs: v6.7.0 sitespeed.io: 4.0.7 browsertime: 1.0.0-beta.11 coach: 0.29.0
[2016-11-19 13:16:41] Starting chrome for analysing https://en.wikipedia.org/wiki/Barack_Obama 3 time(s)
[2016-11-19 13:16:41] Testing url https://en.wikipedia.org/wiki/Barack_Obama run 1
[2016-11-19 13:16:42] https://en.wikipedia.org/wiki/Barack_Obama generated the following error in Browsertime BrowserError: session not created exception
from unknown error: bad inspector message: {"method":"Network.responseReceived","params":{"requestId":"79271.1","frameId":"79271.1","loaderId":"79271.1","timestamp":1656803,712978,"type":"Document","response":{"url":"data:,","status":200,000000,"statusText":"OK","headers":{"Access-Control-Allow-Origin":"*","Content-Type":"text/plain;charset=US-ASCII"},"mimeType":"text/plain","connectionReused":false,"connectionId":0,000000,"fromDiskCache":false,"fromServiceWorker":false,"encodedDataLength":-1,000000,"protocol":"data","securityState":"unknown"}}}
  (Session info: chrome=54.0.2840.98)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.11.6 x86_64)
from unknown error: bad inspector message: {"method":"Network.responseReceived","params":{"requestId":"79271.1","frameId":"79271.1","loaderId":"79271.1","timestamp":1656803,712978,"type":"Document","response":{"url":"data:,","status":200,000000,"statusText":"OK","headers":{"Access-Control-Allow-Origin":"*","Content-Type":"text/plain;charset=US-ASCII"},"mimeType":"text/plain","connectionReused":false,"connectionId":0,000000,"fromDiskCache":false,"fromServiceWorker":false,"encodedDataLength":-1,000000,"protocol":"data","securityState":"unknown"}}}
  (Session info: chrome=54.0.2840.98)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.11.6 x86_64)
    at BrowsertimeError (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/support/errors.js:5:5)
    at BrowserError (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/support/errors.js:13:5)
    at startBrowser.call.catch.tap.tap.catch.catch (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:74:15)
From previous event:
    at SeleniumRunner.start (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:73:13)
    at runIteration (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:202:21)
    at Promise.reduce (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:277:25)
From previous event:
    at Promise.resolve.tap.tap.tap (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:276:17)
From previous event:
    at Engine.run (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:275:8)
    at engine.start.then (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:76:26)
From previous event:
    at Object.analyzeUrl (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:76:8)
    at Object.processMessage (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:129:27)
    at queue.process (/usr/local/lib/node_modules/sitespeed.io/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by tobli** [comment]
Hi!
Selenium (that Browsertime uses to control the browser) requires node 6.9. Please upgrade and see if the issue persists.

**Comment by soulgalore** [comment]
Hi @fhemberger ! I think this is the same error as https://github.com/sitespeedio/sitespeed.io/issues/1275  (right @tobli). There's a bug in Chrome that if you run your OS localized (it happens if you have Swedish and I guess German or whatever European language that uses , instead of .).

It's fixed in Chrome but not released yet. You can use canary and it will hopefully work.

Best
Peter

**Comment by tobli** [comment]
Ahh, yes. That makes sense!

**Comment by fhemberger** [comment]
Yay, thanks for the hint!

`sitespeed.io https://en.wikipedia.org/wiki/Barack_Obama --browser chrome --browsertime.chrome.binaryPath /Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary` worked.

Maybe you can add this to the docs somewhere (at least `--browsertime.chrome.binaryPath` is not listed as valid option in `sitespeed.io --help`)?

**Comment by soulgalore** [comment]
yes agree @fhemberger we have PR for showing all browsertimes cli options automagically in sitespeed.io, that will fix that!
