### ISSUE TITLE
how to run on ubuntu cloud server with limited resources

### ISSUE THREAD

**Issue by viinay** [sitespeedio/browsertime#243]
I was trying to run browsertime on ubuntu cloud server I got following error:

root@vps:~/bro/test# browsertime -u http://www.sitespeed.io -n 1 -b firefox
Starting proxy on port 2001, will wait at most 15000 ms
Fetching http://www.sitespeed.io (1 of 1)
Error: Timed out waiting for the WebDriver server at http://127.0.0.1:59111/hub
    at Error (native)
    at onError (/root/.nvm/versions/node/v6.5.0/lib/node_modules/browsertime/node_modules/selenium-webdriver/http/util.js:87:11)
    at ManagedPromise.invokeCallback_ (/root/.nvm/versions/node/v6.5.0/lib/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/root/.nvm/versions/node/v6.5.0/lib/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/root/.nvm/versions/node/v6.5.0/lib/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at asyncRun (/root/.nvm/versions/node/v6.5.0/lib/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:2775:27)
    at /root/.nvm/versions/node/v6.5.0/lib/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/root/.nvm/versions/node/v6.5.0/lib/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
    at Driver (/root/.nvm/versions/node/v6.5.0/lib/node_modules/browsertime/node_modules/selenium-webdriver/firefox/index.js:386:38)
    at Builder.build (/root/.nvm/versions/node/v6.5.0/lib/node_modules/browsertime/node_modules/selenium-webdriver/builder.js:467:16)
    at Object.module.exports.getDriver (/root/.nvm/versions/node/v6.5.0/lib/node_modules/browsertime/lib/browsers/firefox.js:44:51)
    at /root/.nvm/versions/node/v6.5.0/lib/node_modules/browsertime/lib/browsertime.js:107:64
    at /root/.nvm/versions/node/v6.5.0/lib/node_modules/browsertime/node_modules/async/lib/async.js:726:13
    at /root/.nvm/versions/node/v6.5.0/lib/node_modules/browsertime/node_modules/async/lib/async.js:52:16
    at /root/.nvm/versions/node/v6.5.0/lib/node_modules/browsertime/node_modules/async/lib/async.js:269:32
    at /root/.nvm/versions/node/v6.5.0/lib/node_modules/browsertime/node_modules/async/lib/async.js:44:16
    at /root/.nvm/versions/node/v6.5.0/lib/node_modules/browsertime/node_modules/async/lib/async.js:723:17
Timed out waiting for the WebDriver server at http://127.0.0.1:59111/hub
Stopping proxy

How do i solve this?

**Comment by soulgalore** [comment]
Hey @viinay I think you should use the latest beta of Browsertime, it has less memory impact since it doesn't use Java.

How small is the instance? Both Chrome & Firefox is memory/CPU intensive and tend to use quite much. For instance on Digital Ocean we tend to use a 8 gb with 4 cores to get stable values for larger websites.

Best
Peter

**Comment by soulgalore** [comment]
Didn't get any feedback on my answer, closing.
