### ISSUE TITLE
Add support for Basic Auth

### ISSUE THREAD

**Issue by jpvincent** [sitespeedio/browsertime#254]
We would need to test URLs that are HTTP Auth protected.
Right now the only way is to add the name/pw in front of the URL but it would of course be nice to not need that. 

Selenium does not provide the functionality out of the box, so it seems people modify the URL in their scripts and manipulate the browser preferences. Eg : http://seleniumwebdrivertrainings.com/how-to-perform-basic-authentication-for-firefoxdriver-chromedriver-iedriver-in-selenium-webdriver/

Pre-1.0, the option has existed with this syntax : basicAuth=login:pwd

**Comment by tobli** [comment]
Hi!
Now that we have https://github.com/sitespeedio/browsertime-extension, we should be able to do this.

**Comment by soulgalore** [comment]
Seems it will come in FF54 (already works in Chrome): https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/onAuthRequired

**Comment by tobli** [comment]
👍🏻

**Comment by soulgalore** [comment]
To make it clear, this works in Chrome at the moment, we just wait for @tobli fix in Selenium to be released and FF 54 to be released.

**Comment by mrjcleaver** [comment]
This doesn't work for me in Version 61.0.3163.100 (Official Build) (64-bit) on Mac OS
[2017-10-04 14:34:27] INFO: Versions OS: darwin 16.7.0 nodejs: v8.4.0 sitespeed.io: 5.6.3 browsertime: 1.9.3 coach: 0.36.0

**Comment by soulgalore** [comment]
@mrjcleaver if you try `sitespeed.io http://httpbin.org/basic-auth/user/passwd --browsertime.basicAuth user@passwd` does that work?

**Comment by mrjcleaver** [comment]
`Martins-MacBook-Pro:site-speed martincleaver$ sitespeed.io http://httpbin.org/basic-auth/user/passwd --browsertime.basicAuth user@passwd 
[2017-10-04 15:09:33] INFO: Versions OS: darwin 16.7.0 nodejs: v8.4.0 sitespeed.io: 5.6.3 browsertime: 1.9.3 coach: 0.36.0
[2017-10-04 15:09:34] INFO: Starting chrome for analysing http://httpbin.org/basic-auth/user/passwd 3 time(s)
[2017-10-04 15:09:34] INFO: Testing url http://httpbin.org/basic-auth/user/passwd run 1
[2017-10-04 15:09:38] INFO: Testing url http://httpbin.org/basic-auth/user/passwd run 2
[2017-10-04 15:09:43] INFO: Testing url http://httpbin.org/basic-auth/user/passwd run 3
[2017-10-04 15:09:47] INFO: 3 requests, 603 bytes, backEndTime: 171ms (±7.55ms), firstPaint: 203ms (±8.29ms), DOMContentLoaded: 183ms (±7.79ms), Load: 183ms (±7.79ms), rumSpeedIndex: 203 (±8.29) (3 runs)
[2017-10-04 15:09:49] INFO: HTML stored in /.../site-speed/sitespeed-result/httpbin.org/2017-10-04-15-09-33
[2017-10-04 15:09:49] INFO: Finished analysing http://httpbin.org/basic-auth/user/passwd`

Sure does...

**Comment by mrjcleaver** [comment]
![2017-10-04 15-11-37](https://user-images.githubusercontent.com/59202/31194845-5dd97154-a916-11e7-92ba-a4d06af7d516.png)

**Comment by mrjcleaver** [comment]
![2017-10-04 15-12-33](https://user-images.githubusercontent.com/59202/31194892-8171bba8-a916-11e7-8ffa-9e05f29bf52e.png)

**Comment by mrjcleaver** [comment]
Ok. Looks like it must have a trailing slash on the URL! Works now, thanks.

`[2017-10-04 15:14:44] ERROR: TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:179:11)
    at new Buffer (buffer.js:154:17)
    at Promise.resolve.then.base64EncodedPng (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:183:27)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)`

**Comment by soulgalore** [comment]
This should work with our web extension. Please re-open if there are still issues.
