### ISSUE TITLE
Example login script for Wikipedia doesn't work in Firefox

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#256]
The example script  https://github.com/sitespeedio/browsertime/blob/master/test/prepostscripts/preLoginExample.js doesn't work in Firefox:

<pre>
[2017-01-12 01:49:42] UnknownCommandError: POST /session/a9d3fab6-4168-4e95-8f64-4bc0dbbf70ee/element/d262004d-8acf-4350-8fed-d49e85952246/submit did not match a known command
    at WebDriverError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:27:5)
    at UnknownCommandError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:296:5)
    at Object.throwDecodedError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:477:11)
    at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:499:15)
    at doSend.then.response (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Driver.schedule (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
    at WebElementPromise.schedule_ (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:1921:25)
    at WebElementPromise.submit (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:2246:17)
    at driver.get.then (/sitespeed.io/wikpedia.org-login.txt:28:21)
    at ManagedPromise.invokeCallback_ (/usr/src/app/node_modules/selenium-webdriver/lib/promise.js:1366:14)
    at TaskQueue.execute_ (/usr/src/app/node_modules/selenium-webdriver/lib/promise.js:2970:14)
    at TaskQueue.executeNext_ (/usr/src/app/node_modules/selenium-webdriver/lib/promise.js:2953:27)
    at asyncRun (/usr/src/app/node_modules/selenium-webdriver/lib/promise.js:2813:27)
    at /usr/src/app/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From previous event:
    at runner.start.tap (/usr/src/app/node_modules/browsertime/lib/core/engine.js:211:28)
</pre>
Is it Selenium or Geckodriver?

**Comment by soulgalore** [comment]
We need a better fix!

**Comment by soulgalore** [comment]
It is still not working because of Geckodriver & Selenium.

**Comment by mrajiullah** [comment]
It is still not working  bin/browsertime.js --preScript login_wiki.js -b firefox https://en.wikipedia.org/wiki/Barack_Obama  -n 1

**Comment by soulgalore** [comment]
I haven't looked into it since we are waiting on Firefox to be able to export the HAR again. But we updated Geckodriver to latest, so if we still have the issue, it could be that the example script use non cross compatible Selenium, if you have time @mrajiullah please have look, maybe it's easy to spot.

**Comment by soulgalore** [comment]
This was fixed a couple of days ago!
