### ISSUE TITLE
Use browsertime programmatically & automatisation

### ISSUE THREAD

**Issue by lerayj** [sitespeedio/browsertime#278]
Hi, I'm trying to make work BrowserTime behind a REST API to generate Har and reports on demand from a server.

When I during prototyping on localhost everything work fine. I forked the repo on my project then execute programmatically:
`exec('browsertime-master/bin/browsertime.js ' + urlToReport + ' --resultDir ' + saveDir + " --pageCompleteCheck " + snippet, function(err, out, code) {//whatever}`

Once deployed on Heroku server, I get an error directly after the execution:
```
2017-02-23T15:56:48.077174+00:00 app[web.1]: Error: { Error: Command failed: browsertime-master/bin/browsertime.js http://www.alinea.fr/ --resultDir browsertime-results/www.alinea.fr//2017-02-23T15:56:47.293Z --pageCompleteCheck 'return new Date().valueOf() > window.performance.timing.loadEventEnd + 30000'
2017-02-23T15:56:48.077188+00:00 app[web.1]: [2017-02-23 15:56:48] Error running browsertime BrowserError: Server terminated early with status 2
2017-02-23T15:56:48.077189+00:00 app[web.1]:     at BrowsertimeError (/app/browsertime-master/lib/support/errors.js:5:5)
2017-02-23T15:56:48.077190+00:00 app[web.1]:     at BrowserError (/app/browsertime-master/lib/support/errors.js:13:5)
2017-02-23T15:56:48.077190+00:00 app[web.1]:     at startBrowser.call.catch.tap.tap.catch.catch (/app/browsertime-master/lib/core/seleniumRunner.js:81:15)
2017-02-23T15:56:48.077191+00:00 app[web.1]: From previous event:
2017-02-23T15:56:48.077192+00:00 app[web.1]:     at SeleniumRunner.start (/app/browsertime-master/lib/core/seleniumRunner.js:80:13)
2017-02-23T15:56:48.077192+00:00 app[web.1]:     at runIteration (/app/browsertime-master/lib/core/engine.js:201:21)
2017-02-23T15:56:48.077193+00:00 app[web.1]:     at Promise.reduce (/app/browsertime-master/lib/core/engine.js:279:25)
2017-02-23T15:56:48.077193+00:00 app[web.1]: From previous event:
2017-02-23T15:56:48.077194+00:00 app[web.1]:     at Promise.resolve.tap.tap.tap (/app/browsertime-master/lib/core/engine.js:278:17) 
```
So here are my questions:

- Can we use browsertime on a server?
- Do we need chrome or firefox installed on this machine to make it work?
- How can I parallelise multiple BrowserTime reports generation?
- Could we make a way to make project depending on Browsertime locally and require it (like XrayPage, be able to use it properly with node)?

I guess it's possible since the Docker images is working properly.

I'm still really new on browser emulation&others, I hope my questions make sense...

**Comment by worenga** [comment]
> Can we use browsertime on a server?
Yes. 

> Do we need chrome or firefox installed on this machine to make it work?
Yes, it depends on which browser you want to create the HAR from.

> How can I parallelise multiple BrowserTime reports generation?
I had bad experiences with running multiple browsertime processes concurrently,
i would advertise to start individual docker instances.

Browsertime starts chrome at default, that does not seem to work. Is chrome installed on your machine? Note on a server you might run browsertime in headless mode using xvfb, since there is no x server. I think the easiest solution is to use the docker image here.

BTW: By default browsertime starts 3 runs. if you are only interested in getting the .har one run is sufficient.

**Comment by soulgalore** [comment]
> Could we make a way to make project depending on Browsertime locally and require it (like XrayPage, be able to use it properly with node)?

Yes, you can check how we use it in [sitespeed.io](https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/browsertime/analyzer.js) or the [Coach](https://github.com/sitespeedio/coach/blob/master/lib/index.js)!

**Comment by lerayj** [comment]
I tried with the xvfb option, i have a new issue:
```
Error: { Error: Command failed: browsertime-master/bin/browsertime.js --xvfb http://www.alinea.fr/ --resultDir browsertime-results/www.alinea.fr//2017-02-23T17:01:41.370Z --pageCompleteCheck 'return new Date().valueOf() > window.performance.timing.loadEventEnd + 30000'
[2017-02-23 18:01:42] Error running browsertime {"cause":{"code":"ENOENT","errno":"ENOENT","syscall":"spawn Xvfb","path":"Xvfb","spawnargs":[":99","-ac","-nolisten","tcp","-screen",0,"1200x960x24"]},"isOperational":true,"code":"ENOENT","errno":"ENOENT","syscall":"spawn Xvfb","path":"Xvfb","spawnargs":[":99","-ac","-nolisten","tcp","-screen",0,"1200x960x24"]}
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at Object.startXvfb (/Users/julien/Perso/HealthBook/browsertime-master/lib/support/video/xvfb.js:24:17)
    at Engine.startXvfb (/Users/julien/Perso/HealthBook/browsertime-master/lib/core/engine.js:80:19)
    at Engine.start (/Users/julien/Perso/HealthBook/browsertime-master/lib/core/engine.js:96:30)
    at run (/Users/julien/Perso/HealthBook/browsertime-master/bin/browsertime.js:52:8)
    at Object.<anonymous> (/Users/julien/Perso/HealthBook/browsertime-master/bin/browsertime.js:110:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

> I had bad experiences with running multiple browsertime processes concurrently,
> i would advertise to start individual docker instances.

I was thinking of this if I couldn't find any other alternative.

> Is chrome installed on your machine?

I actually don't know (I guess not), I deployed the project on an Heroku instance. 

> [...] i would advertise to start individual docker instances.

How would you do that? Starting on demand a Docker instance each time I want a report?

> Yes, you can check how we use it in sitespeed.io or the Coach!

@soulgalore Will do it for sure, thanks!

Other randoms questions:

> Is xvfb a concurrent of phantom.js?
> If yes, wouldn't it be easier to make parallel processing with phantom to get the HAR file? (I'm waiting 1min before collection the HAR file, to get all async call done on the page)

Thanks a lot for your answers, I love what you are building, hope I could help in the future when I will be a little more documented on the subject!

BTW: Why using bluebird for promise? Isn't the standard one lacking of something?

**Comment by soulgalore** [comment]
I think you are missing xvfb on the server. It's a virtual framebuffer that can act as a screen, so if you run on a server that doesn't have a screen, xvfb can be used. You will need xvfb, Chrome/Docker and if you want SpeedIndex and other metrics you will need [these](https://github.com/sitespeedio/docker-visualmetrics-deps/blob/master/Dockerfile) dependencies. As @worenga said, if you can run Docker it will be much easier.

There's more info how things work at https://www.sitespeed.io where you can start to get a feel of what you can do and how works.

Yep Bluebird has more functionality out of the box, at least when we started.

**Comment by lerayj** [comment]
Thanks for the answers;
Just wanted a little specification on the PhantomJs question : 

- Is xvfb a concurrent of phantom.js?
- If yes, wouldn't it be easier to make parallel processing (and server side process) with phantom to get the HAR file?

If I well understand, HAR file are generated by the browser. 

Does that means that Firefox HAR and Chrome HAR could be anyway different?

**Comment by tobli** [comment]
Hi!
PhantomJS is a scriptable browser engine, and xvfb is a window manager for Linux (that allows Chrome and Firefox to run on a command line only setup). You can read our blog post from when 4.0 was released for some background why we're not using PhantomJS anymore. https://www.sitespeed.io/sitespeed.io-4.0-is-released/

**Comment by lerayj** [comment]
@tobli Thanks! It's exactly the information I was looking for!

**Comment by abhi7288** [comment]
Hi All, 

I am new to Sitespeedio. I am trying to collect the front end metrics for my organization like time to first byte, TTLB, DOM load time etc. I want to use sitespeedio/browsertime programmitically. Can anyone please provide me some example/examples on how I can do it.?
