### ISSUE TITLE
Long term goal: continue with the rest of the runs if ones fails

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#302]
In this example, the third run fails (note this happens extremely rare) and we stop and report back nothing. I think we should use what we have (2 successful runs) + continue with the next? I also wonder if the retry functionality is broken because this should have been catched or is "exited abnormally" something we can't handle?

<pre>
[2017-04-02 06:00:39] INFO: Testing url https://en.wikipedia.org/wiki/Sweden run 2
[2017-04-02 06:01:11] INFO: Testing url https://en.wikipedia.org/wiki/Sweden run 3
[2017-04-02 06:02:11] ERROR: https://en.wikipedia.org/wiki/Sweden generated the following error in Browsertime BrowserError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.28.455506 (18f6627e265f442aeec9b6661a49fe819aeeea1f),platform=Linux 4.4.0-47-generic x86_64)
  (Driver info: chromedriver=2.28.455506 (18f6627e265f442aeec9b6661a49fe819aeeea1f),platform=Linux 4.4.0-47-generic x86_64)
    at BrowsertimeError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:5:5)
    at BrowserError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:13:5)
    at startBrowser.call.catch.tap.tap.catch.catch (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:85:15)
From previous event:
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:84:13)
    at Promise.resolve.tap (/usr/src/app/node_modules/browsertime/lib/core/engine.js:213:27)
From previous event:
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:213:10)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:297:25)
From previous event:
    at Promise.resolve.tap.tap.tap.tap (/usr/src/app/node_modules/browsertime/lib/core/engine.js:296:17)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine.js:295:8)
    at engine.start.then (/usr/src/app/lib/plugins/browsertime/analyzer.js:76:26)
    at /usr/src/app/node_modules/xvfb/index.js:55:28
    at FSReqWrap.cb [as oncomplete] (fs.js:257:19)
From previous event:
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:76:8)
    at storageManager.createDirForUrl.then.then (/usr/src/app/lib/plugins/browsertime/index.js:134:34)
    at /usr/src/app/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:134:14)
    at queue.process (/usr/src/app/lib/support/queueHandler.js:155:57)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
[2017-04-02 06:02:11] INFO: Starting chrome for analysing https://en.wikipedia.org/wiki/Barack_Obama 5 time(s)
[2017-04-02 06:02:11] INFO: Testing url https://en.wikipedia.org/wiki/Barack_Obama run 1
</pre>

**Comment by worenga** [comment]
I would love to see a solution for this. In my experiments sometimes I visit pages 30-100 times. If one run fails everything is gone. For this reason i changed my scripts to always only execute batches of 10, which is also not optimal because one has to merge the browsertime.har and browsertime.json files in postprocessing.

**Comment by soulgalore** [comment]
can you share tracelogs to see if it is the same or happens in other places too? We have "second try" that normally should kick in, but I guess the long term is to continue with the rest of the runs.

**Comment by tobli** [comment]
From what I can recall, I've only seen this with Chrome. However I don't know if it's Chrome or Chromedriver that's having issues, would love some insights on that. Could we come up with a better strategy for these scenarios? Would introducing delays before retrying help?

**Comment by soulgalore** [comment]
but I think in tha case we did't retry @tobli ? Haven't had time to look at the code yet.

**Comment by tobli** [comment]
Right, we didn't trigger our retry logic that relies on selenium (and by extension Chrome/chromedriver) not returning in time. However if there's an internal timeout in selenium or chromedriver that might trigger first, and return an error. So a too long timeout in Browsertime might actually be counterproductive. I guess we could try catching all types of errors from starting the browser, and retry.

**Comment by soulgalore** [comment]
yep you are right, let us just catch error instead. Worst case it will try multiple time if you lack Chrome in your path?

**Comment by soulgalore** [comment]
will be fixed with https://github.com/sitespeedio/browsertime/pull/506

**Comment by soulgalore** [comment]
This is fixed in master now 💃
