### ISSUE TITLE
Geckodriver 0.16.0 fails getting the HAR on some URLs

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#321]
Using Geckodriver 0.16.0 on my Mac:
<code> bin/browsertime.js http://httpbin.org/html -b firefox</code>
gives me:
<pre>
[2017-04-22 22:14:30] Couldn't generate the HAR from Firefox from the HAR Export Trigger.
[2017-04-22 22:14:30] Error running browsertime BrowserError: Error in Firefox HAR generation
    at BrowsertimeError (/Users/peter/git/browsertime/lib/support/errors.js:5:5)
    at BrowserError (/Users/peter/git/browsertime/lib/support/errors.js:13:5)
    at runner.runAsyncScript.then (/Users/peter/git/browsertime/lib/core/engineDelegate/firefoxDelegate.js:52:15)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at FirefoxDelegate.onStopIteration (/Users/peter/git/browsertime/lib/core/engineDelegate/firefoxDelegate.js:50:60)
    at Promise.resolve.tap.tap.tap.tap.tap.tap.tap.tap.tap (/Users/peter/git/browsertime/lib/core/engine.js:279:39)
From previous event:
    at runIteration (/Users/peter/git/browsertime/lib/core/engine.js:279:10)
    at Promise.reduce (/Users/peter/git/browsertime/lib/core/engine.js:320:25)
From previous event:
    at Promise.resolve.tap.tap.tap.tap (/Users/peter/git/browsertime/lib/core/engine.js:319:17)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Engine.run (/Users/peter/git/browsertime/lib/core/engine.js:318:8)
    at /Users/peter/git/browsertime/bin/browsertime.js:54:21
From previous event:
    at run (/Users/peter/git/browsertime/bin/browsertime.js:53:6)
    at Object.<anonymous> (/Users/peter/git/browsertime/bin/browsertime.js:110:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
</pre>

But reverting to 0.15.0 it works.

**Comment by soulgalore** [comment]
This only fails on my Mac, it works on Travis and in Docker.

**Comment by soulgalore** [comment]
Actually, it works on one of my Macs and not the other one. We've reverted to 0.15 for now and then we can debug the HAR Export Trigger and see if we can understand the root of the problem.

**Comment by beenanner** [comment]
Tested on my Ubuntu 16.04 machine with Firefox 53 and worked. Will test on my Mac and report back if I have issues.

**Comment by beenanner** [comment]
Ok same issue as reported on my Mac. Not sure if this is related `sleep: using busy loop fallback` but happened on my Firefox 52 and 53 for me. Running Node 7.9.0 and NPM 4.2.0.


```
➜  browsertime git:(master) ✗ bin/browsertime.js http://httpbin.org/html -b firefox
sleep: using busy loop fallback
[2017-04-23 23:57:29] Running firefox for url: http://httpbin.org/html
[2017-04-23 23:57:29] Testing url http://httpbin.org/html run 1
[2017-04-23 23:57:34] Couldn't generate the HAR from Firefox from the HAR Export Trigger.
[2017-04-23 23:57:34] Error running browsertime BrowserError: Error in Firefox HAR generation
    at runner.runAsyncScript.then (/Users/jclee2/github/browsertime/lib/core/engineDelegate/firefoxDelegate.js:52:15)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at FirefoxDelegate.onStopIteration (/Users/jclee2/github/browsertime/lib/core/engineDelegate/firefoxDelegate.js:50:60)
    at Promise.resolve.tap.tap.tap.tap.tap.tap.tap.tap.tap (/Users/jclee2/github/browsertime/lib/core/engine.js:279:39)
From previous event:
    at runIteration (/Users/jclee2/github/browsertime/lib/core/engine.js:279:10)
    at Promise.reduce (/Users/jclee2/github/browsertime/lib/core/engine.js:320:25)
From previous event:
    at Promise.resolve.tap.tap.tap.tap (/Users/jclee2/github/browsertime/lib/core/engine.js:319:17)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Engine.run (/Users/jclee2/github/browsertime/lib/core/engine.js:318:8)
    at /Users/jclee2/github/browsertime/bin/browsertime.js:54:21
From previous event:
    at run (/Users/jclee2/github/browsertime/bin/browsertime.js:53:6)
    at Object.<anonymous> (/Users/jclee2/github/browsertime/bin/browsertime.js:110:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
```

**Comment by beenanner** [comment]
Following for node 6

```
➜  browsertime git:(master) ✗ nvm use 6
Now using node v6.10.0 (npm v3.10.10)
➜  browsertime git:(master) ✗ npm install
➜  browsertime git:(master) ✗ bin/browsertime.js http://httpbin.org/html -b firefox
[2017-04-23 23:59:44] Running firefox for url: http://httpbin.org/html
[2017-04-23 23:59:44] Testing url http://httpbin.org/html run 1
[2017-04-23 23:59:49] Couldn't generate the HAR from Firefox from the HAR Export Trigger.
[2017-04-23 23:59:49] Error running browsertime BrowserError: Error in Firefox HAR generation
    at BrowsertimeError (/Users/jclee2/github/browsertime/lib/support/errors.js:5:5)
    at BrowserError (/Users/jclee2/github/browsertime/lib/support/errors.js:13:5)
    at runner.runAsyncScript.then (/Users/jclee2/github/browsertime/lib/core/engineDelegate/firefoxDelegate.js:52:15)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at FirefoxDelegate.onStopIteration (/Users/jclee2/github/browsertime/lib/core/engineDelegate/firefoxDelegate.js:50:60)
    at Promise.resolve.tap.tap.tap.tap.tap.tap.tap.tap.tap (/Users/jclee2/github/browsertime/lib/core/engine.js:279:39)
From previous event:
    at runIteration (/Users/jclee2/github/browsertime/lib/core/engine.js:279:10)
    at Promise.reduce (/Users/jclee2/github/browsertime/lib/core/engine.js:320:25)
From previous event:
    at Promise.resolve.tap.tap.tap.tap (/Users/jclee2/github/browsertime/lib/core/engine.js:319:17)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Engine.run (/Users/jclee2/github/browsertime/lib/core/engine.js:318:8)
    at /Users/jclee2/github/browsertime/bin/browsertime.js:54:21
From previous event:
    at run (/Users/jclee2/github/browsertime/bin/browsertime.js:53:6)
    at Object.<anonymous> (/Users/jclee2/github/browsertime/bin/browsertime.js:110:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by beenanner** [comment]
Diff for geckodriver reference https://github.com/mozilla/geckodriver/compare/v0.15.0...v0.16.0

**Comment by soulgalore** [comment]
Without 0.16.0 we have the problem error with send keys: https://github.com/mozilla/geckodriver/issues/659

**Comment by sinplanbsoft** [comment]
With this packaje.json
`{
  "name": "selenium",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "geckodriver": "^1.6.0",
    "install": "^0.8.8",
    "npm": "^4.5.0",
    "selenium-webdriver": "^3.4.0"
  }
}`

and this simple code

`require('geckodriver')
var webdriver = require('selenium-webdriver'),
    By = webdriver.By,
    until = webdriver.until;

var driver = new webdriver.Builder()
    .forBrowser('firefox')
    .build();

driver.get('http://www.google.com/ncr');
driver.findElement(By.name('q')).sendKeys('webdriver');
driver.findElement(By.name('btnG')).click();
driver.wait(until.titleIs('webdriver - Google Search'), 1000);
driver.quit();`

I still have the same error when sendKeys:
InvalidArgumentError: Could not convert 'text' to string
    at WebDriverError (C:\playground\sites\selenium\node_modules\selenium-webdriver\lib\error.js:27:5)
    at InvalidArgumentError (C:\playground\sites\selenium\node_modules\selenium-webdriver\lib\error.js:64:5)
    at Object.throwDecodedError (C:\playground\sites\selenium\node_modules\selenium-webdriver\lib\error.js:489:11)
    at parseHttpResponse (C:\playground\sites\selenium\node_modules\selenium-webdriver\lib\http.js:519:13)
    at doSend.then.response (C:\playground\sites\selenium\node_modules\selenium-webdriver\lib\http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebElement.sendKeys()

**Comment by soulgalore** [comment]
Hey @sinplanbsoft yeah could be that there are more things that needs to be fixed in Geckodriver, could please check if you see an issue for that at https://github.com/mozilla/geckodriver and if you don't find, file an issue? 

Thanks!
Peter

**Comment by soulgalore** [comment]
Ah I see, it still the same right, so it should be re-opened at Geckodriver. I got another message before so I thought I come a little further now but probably not then.

**Comment by soulgalore** [comment]
Could be that this a problem for NodeJS version of Selenium.

**Comment by soulgalore** [comment]
There's a fix for that in Selenium: https://github.com/SeleniumHQ/selenium/pull/3905

**Comment by soulgalore** [comment]
Upgrading to 0.17.0 and it is magically fixed.
