### ISSUE TITLE
Upgrading to FF 55 make runs fails

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#358]
When we pushed 55 in the Docker container we got a lot of errors like:

```
[2017-08-16 04:39:01] INFO: Starting firefox for analysing https://www.sitespeed.io/ 3 time(s)
[2017-08-16 04:39:01] Testing url https://www.sitespeed.io/ run 1
[2017-08-16 04:40:34] Couldn't generate the HAR from Firefox from the HAR Export Trigger.
[2017-08-16 04:40:35] ERROR: ScriptTimeoutError: Timed out
    at WebDriverError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:27:5)
    at ScriptTimeoutError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:211:5)
    at Object.throwDecodedError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:497:15)
    at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:519:13)
    at doSend.then.response (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
    at Driver.schedule (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at Driver.executeAsyncScript (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:891:17)
    at Promise.try (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:187:28)
From previous event:
    at SeleniumRunner.runAsyncScript (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:181:11)
    at FirefoxDelegate.onStopIteration (/usr/src/app/node_modules/browsertime/lib/core/engineDelegate/firefoxDelegate.js:50:19)
    at Promise.resolve.tap.tap.tap.tap.tap.tap.tap.tap.tap (/usr/src/app/node_modules/browsertime/lib/core/engine.js:285:39)
From previous event:
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:285:10)
    at Promise.reduce (/usr/src/app/node_m
```

I think we also got in Travis so I'll make sure we run 54 for a while. On my Mac it worked when I did a  simple test yesterday, but I need to test some more.

**Comment by soulgalore** [comment]
Well, I hadn't upgraded to 55 on this computer (the auto update is broken between 54 and 55 so you need to automatically download it on Mac at least). When I installed 55 I get the same on Mac.

**Comment by soulgalore** [comment]
Filed an issue here:https://github.com/firebug/har-export-trigger/issues/53

**Comment by stephendonner** [comment]
FWIW, the issue with not automatically being updated/offered to download Firefox 55 was https://bugzilla.mozilla.org/show_bug.cgi?id=1389506

**Comment by soulgalore** [comment]
3.0 will be released with FF 60 in beta in the container where we use the new export trigger.
