### ISSUE TITLE
--pageCompleteCheck Exception

### ISSUE THREAD

**Issue by scabenga** [sitespeedio/browsertime#430]
Hello!

I hope someone can assist with this, I am loading a URL and trying to specify when the page stops loading using --pageCompleteCheck.

My JS (which i'm a novice in) looks like this:
```
if (document.getElementsByClassName("xyz")) {
        return true;
    }
```
I am calling is like so:

docker run --shm-size=1g --rm -v "$(pwd)":/browsertime sitespeedio/browsertime --outputFolder=/Users/scab/ --pageCompleteCheck=/Users/scab/Documents/sitespeed_io/find_class.js https://thisistheurl.com/somepath/ -n 1 --mobile

and this is the error:

[2018-01-23 14:11:09] Catched a WebDriverError [unknown error: Runtime.evaluate threw exception: SyntaxError: Invalid regular expression flags
  (Session info: chrome=63.0.3239.84)
  (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.9.60-linuxkit-aufs x86_64)]. Try one more time.WebDriverError: unknown error: Runtime.evaluate threw exception: SyntaxError: Invalid regular expression flags
  (Session info: chrome=63.0.3239.84)
  (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.9.60-linuxkit-aufs x86_64)
[2018-01-23 14:11:14] WebDriverError:WebDriverError: unknown error: Runtime.evaluate threw exception: SyntaxError: Invalid regular expression flags
  (Session info: chrome=63.0.3239.84)
  (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.9.60-linuxkit-aufs x86_64)
[2018-01-23 14:11:14] Could not load URLUrlLoadError: Failed to load https://thisistheurl.com/somepath/, cause: unknown error: Runtime.evaluate threw exception: SyntaxError: Invalid regular expression flags
  (Session info: chrome=63.0.3239.84)
  (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.9.60-linuxkit-aufs x86_64)
[2018-01-23 14:11:14] Error running browsertime UrlLoadError: Failed to load https://thisistheurl.com/somepath/
    at getUrl.then.then.catch.catch.e (/usr/src/app/lib/core/seleniumRunner.js:176:15)
From previous event:
    at SeleniumRunner.loadAndWait (/usr/src/app/lib/core/seleniumRunner.js:174:13)
    at Promise.resolve.tap.tap.tap.tap.tap (/usr/src/app/lib/core/engine.js:250:27)
From previous event:
    at runIteration (/usr/src/app/lib/core/engine.js:250:10)
    at Promise.reduce (/usr/src/app/lib/core/engine.js:330:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/usr/src/app/lib/core/engine.js:327:17)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Engine.run (/usr/src/app/lib/core/engine.js:326:8)
    at /usr/src/app/bin/browsertime.js:63:21
From previous event:
    at run (/usr/src/app/bin/browsertime.js:62:6)
    at Object.<anonymous> (/usr/src/app/bin/browsertime.js:137:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

Any ideas what i am doing wrong?

Thanks!

**Comment by soulgalore** [comment]
Hi @scabenga you should add the script as oneliner instead of a file, this is how you do it in sitespeed.io https://www.sitespeed.io/documentation/sitespeed.io/browsers/#choose-when-to-end-your-test 

Best
Peter

**Comment by tobli** [comment]
One additional tip: check your javascript in the devtools console, to quickly verify that it works as expected. getElementsByClassName returns an HTMLCollection which, maybe surprisingly, evaluates to true even if empty. Try the following:
```js
if (document.getElementsByClassName("this-does–not-exists")) {
        console.log("This was unexpected...");
    }
```

This is probably what you want: ```return (document.getElementsByClassName("xyz").length > 0)```

**Comment by scabenga** [comment]
Thanks for the assistance here guys, will do some further testing.

**Comment by scabenga** [comment]
Hi @tobli and @soulgalore 

I'm not sure if --pageCompleteCheck is working, as when i add some JS to check when a class exists, the test ends long before the class exists.

docker run --shm-size=1g --rm -v "$(pwd)":/browsertime sitespeedio/browsertime --outputFolder=/Users/craigk/ https://theurl.com/path -n 1 --mobile --browsertime.pageCompleteCheck  'return (document.getElementsByClassName("xyz").length > 0)'

The test always ends around 8.5 seconds, and the class loads at +- 20 seconds.

Thanks

**Comment by scabenga** [comment]
Hi @tobli and @soulgalore 

Apologies for spamming this thread.

Here are some examples of issues i am experiencing:

1) When using the below to launch the tests, i get the following error:

`docker run --shm-size=1g --rm -v "$(pwd)":/browsertime sitespeedio/browsertime --outputFolder=/Users/scab/ https://m.news24.com -n 1 --mobile --viewPort 1334x750 --pageCompleteCheck  'return (document.getElementsByClassName("page_content content").length > 0)'`

Google Chrome 63.0.3239.84 
Mozilla Firefox 54.0.1
[2018-01-24 11:57:06] Running chrome for url: https://m.news24.com
[2018-01-24 11:57:06] Testing url https://m.news24.com run 1
[2018-01-24 12:02:17] Could not load URLTimeoutError: Running page complete check 'return' took too long.
[2018-01-24 12:02:17] Error running browsertime UrlLoadError: Failed to load https://m.news24.com
    at getUrl.then.then.catch.catch.e (/usr/src/app/lib/core/seleniumRunner.js:176:15)
From previous event:
    at SeleniumRunner.loadAndWait (/usr/src/app/lib/core/seleniumRunner.js:174:13)
    at Promise.resolve.tap.tap.tap.tap.tap (/usr/src/app/lib/core/engine.js:250:27)
From previous event:
    at runIteration (/usr/src/app/lib/core/engine.js:250:10)
    at Promise.reduce (/usr/src/app/lib/core/engine.js:330:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/usr/src/app/lib/core/engine.js:327:17)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Engine.run (/usr/src/app/lib/core/engine.js:326:8)
    at /usr/src/app/bin/browsertime.js:63:21
From previous event:
    at run (/usr/src/app/bin/browsertime.js:62:6)
    at Object.<anonymous> (/usr/src/app/bin/browsertime.js:137:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

2) When using the below to launch the tests, it completes the test in 8 seconds no matter what class i add to mark it as finished.

`docker run --shm-size=1g --rm -v "$(pwd)":/browsertime sitespeedio/browsertime --outputFolder=/Users/craigk/ https://m.news24.com -n 1 --mobile --viewPort 1334x750 --browsertime.pageCompleteCheck  'return (document.getElementsByClassName("page_content content").length > 0)'`

Google Chrome 63.0.3239.84 
Mozilla Firefox 54.0.1
[2018-01-24 12:04:01] Running chrome for url: https://m.news24.com
[2018-01-24 12:04:01] Testing url https://m.news24.com run 1
[2018-01-24 12:04:27] 117 requests, 865.24 kb, backEndTime: 238ms, firstPaint: 1.99s, firstVisualChange: 2.03s, DOMContentLoaded: 3.88s, Load: 7.06s, speedIndex: 4008, visualComplete85: 4.90s, lastVisualChange: 4.90s, rumSpeedIndex: 4335
[2018-01-24 12:04:27] Wrote data to browsertime-results/m.news24.com/2018-01-24T120400+0000

Should we be using --browsertime.pageCompleteCheck or --pageCompleteCheck?

And when adding the following to the console "document.getElementsByClassName("page_content content").length > 0" i get a "true" response, however when adding "return (document.getElementsByClassName("page_content content").length > 0)", i get "Uncaught SyntaxError: Illegal return statement" response.

**Comment by soulgalore** [comment]
If you run from sitespeed.io, you need to add **browsertime** to propagate the config to browsertime. If you run Browsertime standalone --pageCompleteCheck  is enough. If I add --verbose I can see that the pageCompleteCheck is cut off, when I log the option it looks like this:

` "pageCompleteCheck": "return",`

instead of the full expression. It works fine though if I run directly in Node. @tobli do you see what's wrong?

**Comment by scabenga** [comment]
Thanks @soulgalore !
It would seem that it is terminating at the first space.
On another note, how often is this JS queried?

**Comment by soulgalore** [comment]
There was a bug in the start script that I introduced some time ago, it is fixed in 2.1.7. 

The JS is run ... I don't know, it depends on the webdriver wait method.

**Comment by scabenga** [comment]
Thanks for attending to the bug @soulgalore!

**Comment by scabenga** [comment]
Hi @soulgalore, me again :(
I'm been trying to state when my page has stopped loading and for metrics to be collected, however it would seem that my scrip is not repeatedly queried.

I've used:
`document.getElementsByClassName("classname").length > 1`
Which returns "true" in the chrome console when class becomes available (false before).  The class name becomes available at around 20 seconds.

also tried:
`return (document.getElementsByClassName("classname").length > 1)`

Are you able to have a quick look over when you have a gap?

`docker run --shm-size=1g --rm -v "$(pwd)":/browsertime sitespeedio/browsertime:2.1.7 --outputFolder=/Users/scab/ https://urlinuse/path -n 1 --mobile --viewPort 1334x750 --pageCompleteCheck 'document.getElementsByClassName("classname").length > 1'`

Thanks,
Scabs

**Comment by soulgalore** [comment]
Hi @scabenga 
so I didn't fully get what happens now? Do you get another timeout before the page has finished loading or? 

Best
Peter

**Comment by scabenga** [comment]
Hi Peter,

So i start the test and all looks good, i see the "Waiting for script" a few seconds after the test starts.  It then runs until it times-out, with the error "Running page complete check '(document.getElementsByClassName("classname").length > 1' took too long.".

I hope i am making sense?

Thanks

**Comment by soulgalore** [comment]
Hi @scabenga ok, hmm, there's one setting for how long to wait for the timeout  --timeouts.pageCompleteCheck (https://www.sitespeed.io/documentation/browsertime/configuration/) but that is default 5 min so it "shouldn't" kick in. Not 100% sure why it doesn't work.

best
Peter

**Comment by scabenga** [comment]
@soulgalore so when use add a script using -pageCompleteCheck is is only run once?

**Comment by soulgalore** [comment]
No it should run all the time (if something isn't completely broken). Selenium should take care of that.
