### ISSUE TITLE
Session deleted because error encountered when notifying listeners of 'GetLog' command

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#435]
Got this when running WebPageReplay for the first run (when caching assets). We should fix the original cause +  don't continue if the first run fails.

```
[2018-01-31 11:02:33] Testing url https://en.wikipedia.org/wiki/Barack_Obama run 1
[2018-01-31 11:02:33] Use Chrome trace categories: devtools.timeline
(node:54) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): WebDriverError: unknown error: session deleted because error encountered when notifying listeners of 'GetLog' command
from timeout: Timed out receiving message from renderer: 30.000
  (Session info: chrome=64.0.3282.119)
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.4.0-1049-aws x86_64)
(node:54) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by soulgalore** [comment]
This is a full trace:
```
[2018-02-15 11:53:09] Error running browsertime WebDriverError: unknown error: session deleted because error encountered when notifying listeners of 'GetLog' command
from timeout: Timed out receiving message from renderer: 30.000
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.9.60-linuxkit-aufs x86_64)
from timeout: Timed out receiving message from renderer: 30.000
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.9.60-linuxkit-aufs x86_64)
    at Object.checkLegacyResponse (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Driver.schedule (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at Logs.get (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:1731:25)
    at SeleniumRunner.getLogs (/usr/src/app/lib/core/seleniumRunner.js:238:10)
From previous event:
    at SeleniumRunner.getLogs (/usr/src/app/lib/core/seleniumRunner.js:234:20)
    at ChromeDelegate.onStopIteration (/usr/src/app/lib/core/engineDelegate/chromeDelegate.js:55:31)
    at Promise.resolve.tap.tap.tap.tap.tap.tap.tap.tap.tap.tap.results (/usr/src/app/lib/core/engine.js:299:37)
From previous event:
    at runIteration (/usr/src/app/lib/core/engine.js:299:10)
    at Promise.reduce (/usr/src/app/lib/core/engine.js:348:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/usr/src/app/lib/core/engine.js:345:17)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Engine.run (/usr/src/app/lib/core/engine.js:344:8)
    at /usr/src/app/bin/browsertime.js:63:21
From previous event:
    at run (/usr/src/app/bin/browsertime.js:62:6)
    at Object.<anonymous> (/usr/src/app/bin/browsertime.js:138:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by soulgalore** [comment]
This seems to have been fixed in 3.x.
