### ISSUE TITLE
Error running browsertime ScriptTimeoutError: Timed out

### ISSUE THREAD

**Issue by mrajiullah** [sitespeedio/browsertime#440]
Hi!

I am using firefox version 56 and browser time 2.1.3 
And I done use HAR export 

cmd=['bin/browsertime.js','-b',"firefox","https://"+str(url), 
				'-n','1','--resultDir','web-res','--skipHar',
				'--firefox.preference', 'network.http.spdy.enabled:false', 
				'--firefox.preference', 'network.http.spdy.enabled.http2:false', 
				'--firefox.preference', 'network.http.spdy.enabled.v3-1:false',  
				'--userAgent', '"Mozilla/5.0 (Android 4.4; Mobile; rv:54.0) Gecko/54.0 Firefox/54.0"']

or

			cmd=['bin/browsertime.js','-b',"firefox","https://"+str(url), 
				'-n','1','--resultDir','web-res','--skipHar'
				'--userAgent', '"Mozilla/5.0 (Android 4.4; Mobile; rv:54.0) Gecko/54.0 Firefox/54.0"']

However, quite often I get the following error of being timed out. Is there any know issue.

 Error running browsertime ScriptTimeoutError: Timed out
    at Object.throwDecodedError (/opt/monroe/node_modules/selenium-webdriver/lib/error.js:514:15)
    at parseHttpResponse (/opt/monroe/node_modules/selenium-webdriver/lib/http.js:519:13)
    at doSend.then.response (/opt/monroe/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Driver.schedule (/opt/monroe/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at Driver.executeAsyncScript (/opt/monroe/node_modules/selenium-webdriver/lib/webdriver.js:891:17)
    at Promise.try (/opt/monroe/lib/core/seleniumRunner.js:225:26)
From previous event:
    at SeleniumRunner.runAsyncScript (/opt/monroe/lib/core/seleniumRunner.js:219:23)
    at FirefoxDelegate.onStopIteration (/opt/monroe/lib/core/engineDelegate/firefoxDelegate.js:46:36)
    at Promise.resolve.tap.tap.tap.tap.tap.tap.tap.tap.tap.results (/opt/monroe/lib/core/engine.js:282:37)
From previous event:
    at runIteration (/opt/monroe/lib/core/engine.js:282:10)
    at Promise.reduce (/opt/monroe/lib/core/engine.js:330:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/opt/monroe/lib/core/engine.js:327:17)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at Engine.run (/opt/monroe/lib/core/engine.js:326:8)
    at /opt/monroe/bin/browsertime.js:63:21
From previous event:
    at run (/opt/monroe/bin/browsertime.js:62:6)
    at Object.<anonymous> (/opt/monroe/bin/browsertime.js:137:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

M. Rajiullah

**Comment by soulgalore** [comment]
Hi @mrajiullah would it be possible to share a URL of one of the failings ones so we can try to reproduce? I've run 58 continuously the same and don't have the error so I think there are some content etc on the site makes it happen and it would be great to know more!

I wonder if it is possible to see which script times out if you turn on --verbose logging, that would help. But I need to actually check the code first, I'm not 100% we do that.

Best
Peter

**Comment by mrajiullah** [comment]
Hi Peter!

I got the timeout error for the following urls while set for http2 

Browsing www.linkedin.com/company/teliacompany with firefox browser and h2 protocol
Browsing www.youtube.com/watch?v=544vEgMiMG0 with firefox browser and h2 protocol
Browsing www.ebay.com with firefox browser and h2 protocol
Browsing www.imgur.com with firefox browser and h2 protocol
Browsing www.facebook.com/telia/ with firefox browser and h2 protocol
Browsing www.coursera.com with firefox browser and h2 protocol
Browsing www.theguardian.com/international with firefox browser and h2 protocol
Browsing www.wikihow.com with firefox browser and h2 protocol
Browsing www.kayak.com with firefox browser and h2 protocol
Browsing www.etsy.com with firefox browser and h2 protocol
Browsing www.wikipedia.org with firefox browser and h2 protocol
Browsing www.nytimes.com with firefox browser and h2 protocol
Browsing www.yelp.com with firefox browser and h2 protocol
Browsing www.stackoverflow.com with firefox browser and h2 protocol
Browsing www.9gag.com with firefox browser and h2 protocol
Browsing www.google.com/#q=stockholm,+sweden with firefox browser and h2 protocol
Browsing www.instagram.com/leomessi/ with firefox browser and h2 protocol

My command for Http2 is 

cmd=['bin/browsertime.js','-b',"firefox","https://"+str(url), 
			'-n','1','--resultDir','web-res','--skipHar'
			'--userAgent', '"Mozilla/5.0 (Android 4.4; Mobile; rv:56.0) Gecko/56.0 Firefox/56.0"']

Mvh,
M. Rajiullah

**Comment by mrajiullah** [comment]
Hi again!

I find the problem. Its silly I missed a comma after the --skipHar
Thanks,
M. Rajiullah
