### ISSUE TITLE
Error (2.5.0, Firefox): Catched a WebDriverError on http://www.elmundo.es

### ISSUE THREAD

**Issue by suratovvlad** [sitespeedio/browsertime#554]
Hi!
There is strange error with website http://www.elmundo.es that I could reproduce with browsertime 2.5.0, and couldn't with 3.0.0-alpha.5:

Google Chrome 63.0.3239.132 
Mozilla Firefox 54.0.1
[2018-04-11 11:14:38] Running firefox for url: http://www.elmundo.es
[2018-04-11 11:14:38] Testing url http://www.elmundo.es run 1
[2018-04-11 11:14:53] Catched a WebDriverError [Reached error page: about:neterror?e=dnsNotFound&u=http%3A//geo-um.btrll.com/v1/map_pixel/partner/1895.png&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20find%20the%20server%20at%20geo-um.btrll.com.]. Try one more time.WebDriverError: Reached error page: about:neterror?e=dnsNotFound&u=http%3A//geo-um.btrll.com/v1/map_pixel/partner/1895.png&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20find%20the%20server%20at%20geo-um.btrll.com.
[2018-04-11 11:16:32] Error running browsertime ScriptTimeoutError: Timed out
    at Object.throwDecodedError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:514:15)
    at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:519:13)
    at doSend.then.response (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Driver.schedule (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at Driver.executeAsyncScript (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:891:17)
    at Promise.try (/usr/src/app/lib/core/seleniumRunner.js:225:26)
From previous event:
    at SeleniumRunner.runAsyncScript (/usr/src/app/lib/core/seleniumRunner.js:219:23)
    at FirefoxDelegate.onStopIteration (/usr/src/app/lib/core/engineDelegate/firefoxDelegate.js:60:38)
    at <anonymous>

The parameters for the run:
`docker run --shm-size=1g -it  -v "$(pwd)":/browsertime sitespeedio/browsertime:2.5.0  --browser firefox -n 1  "http://www.elmundo.es"`

The version 3.0.0-alpha.5 works perfect and returns:

Google Chrome 66.0.3359.33 beta
Mozilla Firefox 61.0a1
[2018-04-11 11:15:26] Running firefox for url: http://www.elmundo.es
[2018-04-11 11:15:27] Testing url http://www.elmundo.es iteration 1
[2018-04-11 11:16:23] Waiting on har-export-trigger to collect the HAR
[2018-04-11 11:17:41] 681 requests, 4294.79 kb, backEndTime: 244ms, firstPaint: 1.99s, DOMContentLoaded: 3.35s, Load: 31.95s, rumSpeedIndex: 2904
[2018-04-11 11:17:41] Wrote data to browsertime-results/www.elmundo.es/2018-04-11T111526+0000

**Comment by soulgalore** [comment]
Hi @suratovvlad thanks for creating the issue. In coming 3.0 we changed how we navigate (we now use JavaScript) maybe that fixed the thing. I hope to be able to write a short blog post of the coming 3 release the coming days.

Best
Peter

**Comment by suratovvlad** [comment]
Hi, @soulgalore !
Thanks a lot for your great work and awesome projects) I hope the coming 3 release would be soon included to the new sitespeed.io!

**Comment by soulgalore** [comment]
New version released, so hope it works!
