### ISSUE TITLE
[NodeJs] [Windows10] HAR Firefox

### ISSUE THREAD

**Issue by GeekZebre** [sitespeedio/browsertime#601]
Since I have updated this day, I have an error with command : 
`$ ./bin/browsertime.js https://www.sitespeed.io/ --n 1 true -vvv --visualMetrics --video -b firefox
`

`[2018-05-22 22:03:22] Waiting on har-export-trigger to collect the HAR
[2018-05-22 22:03:22] Executing async script
    var callback = arguments[arguments.length - 1];
    function triggerExport() {
      HAR.triggerExport()
        .then((result) => {
          // Different handling in FF 60 and 61 :|
          if (result.log) {
            result.log.pages[0].title = document.title;
          }
          else {
            result.pages[0].title = document.title;
          }
          // Normalize
          return callback({'har': result.log ? result: {log: result}});
      })
      .catch((e) => callback({'error': e}));
    };
      triggerExport();

[2018-05-22 22:03:22] Could not get the HAR from Firefox JavascriptError: ReferenceError: HAR is not defined
    at Object.throwDecodedError (D:\GitRepositories\GitHubDesktop\SiteSpeedio\GeekZebre\GitHubDesktop-SiteSpeedio-browsertime\node_modules\selenium-webdriver\lib\error.js:514:15)
    at parseHttpResponse (D:\GitRepositories\GitHubDesktop\SiteSpeedio\GeekZebre\GitHubDesktop-SiteSpeedio-browsertime\node_modules\selenium-webdriver\lib\http.js:519:13)
    at doSend.then.response (D:\GitRepositories\GitHubDesktop\SiteSpeedio\GeekZebre\GitHubDesktop-SiteSpeedio-browsertime\node_modules\selenium-webdriver\lib\http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.executeScript()
    at Driver.schedule (D:\GitRepositories\GitHubDesktop\SiteSpeedio\GeekZebre\GitHubDesktop-SiteSpeedio-browsertime\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
    at Driver.executeAsyncScript (D:\GitRepositories\GitHubDesktop\SiteSpeedio\GeekZebre\GitHubDesktop-SiteSpeedio-browsertime\node_modules\selenium-webdriver\lib\webdriver.js:891:17)
    at SeleniumRunner.runAsyncScript (D:\GitRepositories\GitHubDesktop\SiteSpeedio\GeekZebre\GitHubDesktop-SiteSpeedio-browsertime\lib\core\seleniumRunner.js:264:26)
    at FirefoxDelegate.onStopIteration (D:\GitRepositories\GitHubDesktop\SiteSpeedio\GeekZebre\GitHubDesktop-SiteSpeedio-browsertime\lib\firefox\webdriver\firefoxDelegate.js:70:40)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2018-05-22 22:03:22] Running visualMetrics
`

**Comment by soulgalore** [comment]
Hi @GeekZebre we did a push with the new version of the HAR plugin today, that if you run FF 61 you don't need to choose the network tab. Which Browsertime version are you using and which Firefox?

Best
Peter

**Comment by GeekZebre** [comment]
Hello @soulgalore 
I use FF 60.0.1 (64 bits) and firefox is up to date.
I use the latest version : I make a PR.

**Comment by soulgalore** [comment]
Hmm I think the actual new version of the plugin broke compatibility in FF 60, sorry I missed that when I upgraded. The plugin has worked in 60 but in 61 it will work without needing to enable the network tab. 

I'll rollback to the old version later today (the new also seemed to cause a lot of errors on our test server with content fields missing in the HAR).

Best
Peter

**Comment by soulgalore** [comment]
@GeekZebre released the new version a couple of minutes ago, sorry I missed the incompatibility issue! Will roll on to the new version when 61 becomes stable.

**Comment by GeekZebre** [comment]
Hi @soulgalore 
This doesn't work.

In the bug, 'HAR is not defined'.
It's beacause I Run Firefox 60.0.1 and not Firefox Nightly 62.0a1 (May 7, 2018) (as say in https://github.com/devtools-html/har-export-trigger )

I retest with 'harexporttriggerbrowsertime-0.0.1-an+fx.xpi' and it's work.

The problem come with 'har_export_trigger-0.6.0-an+fx.xpi'.

GeekZebre.

**Comment by soulgalore** [comment]
Yep you are right, the official plugin doesn't work with 60 :(

**Comment by soulgalore** [comment]
We released so you need to use FF 61 to get the HAR (included in the container). If you run version < 61 you will get a log message telling you need to run 61 to get the HAR.
