### ISSUE TITLE
ERROR: WebDriverError: chrome not reachable

### ISSUE THREAD

**Issue by WinNajeem** [sitespeedio/browsertime#617]
Hello.

Im getting below error while trying to hit url.
docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io --browsertime.iterations 1 --browsertime.browser chrome --no-sandbox --firstParty ".ebiztest.com" http://www.ebiztest.com

Even tried without the --no-sandbox argument and the command still continue to fail.
Failure also create core files.

[2018-07-03 04:07:58] INFO: Starting chrome for analysing http://www.ebiztest.com 1 time(s)
[2018-07-03 04:07:58] INFO: Testing url http://www.ebiztest.com iteration 1
[2018-07-03 04:08:27] ERROR: WebDriverError: chrome not reachable
  (Session info: chrome=67.0.3396.99)
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 3.10.0-693.11.1.el7.x86_64 x86_64)
  (Session info: chrome=67.0.3396.99)
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 3.10.0-693.11.1.el7.x86_64 x86_64)
    at Object.checkLegacyResponse (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.executeScript()
    at Driver.schedule (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at Driver.executeScript (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:878:16)
    at SeleniumRunner.runScript (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:240:21)
    at SeleniumRunner.runScriptFromCategory (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:340:19)
    at SeleniumRunner.runScriptInCategory (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:376:33)
    at SeleniumRunner.runScripts (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:361:42)
    at Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:133:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by dineshrathee12** [comment]
node:2987) UnhandledPromiseRejectionWarning: WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.26.436382 (70eb799287ce4c2208441fc057053a5b07ceabac),platform=Linux 4.4.0-1075-aws x86_64)
    at Object.checkLegacyResponse (/opt/bitnami/apache2/htdocs/node_modules/selenium-webdriver/lib/error.js:585:15)
    at parseHttpResponse (/opt/bitnami/apache2/htdocs/node_modules/selenium-webdriver/lib/http.js:533:13)
    at Executor.execute (/opt/bitnami/apache2/htdocs/node_modules/selenium-webdriver/lib/http.js:468:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2987) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async f
unction without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2987) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not ha
ndled will terminate the Node.js process with a non-zero exit code.
(node:2987) UnhandledPromiseRejectionWarning: WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.26.436382 (70eb799287ce4c2208441fc057053a5b07ceabac),platform=Linux 4.4.0-1075-aws x86_64)
    at Object.checkLegacyResponse (/opt/bitnami/apache2/htdocs/node_modules/selenium-webdriver/lib/error.js:585:15)
    at parseHttpResponse (/opt/bitnami/apache2/htdocs/node_modules/selenium-webdriver/lib/http.js:533:13)
    at Executor.execute (/opt/bitnami/apache2/htdocs/node_modules/selenium-webdriver/lib/http.js:468:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2987) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async f
unction without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2987) UnhandledPromiseRejectionWarning: WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.26.436382 (70eb799287ce4c2208441fc057053a5b07ceabac),platform=Linux 4.4.0-1075-aws x86_64)
    at Object.checkLegacyResponse (/opt/bitnami/apache2/htdocs/node_modules/selenium-webdriver/lib/error.js:585:15)
    at parseHttpResponse (/opt/bitnami/apache2/htdocs/node_modules/selenium-webdriver/lib/http.js:533:13)
    at Executor.execute (/opt/bitnami/apache2/htdocs/node_modules/selenium-webdriver/lib/http.js:468:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2987) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async f
unction without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

**Comment by dineshrathee12** [comment]
Pls suggest :)

**Comment by soulgalore** [comment]
Hi @dineshrathee12 could you please create a new issue for this and show me how you run so I can recreate it? https://www.sitespeed.io/documentation/sitespeed.io/bug-report/#explain-how-to-reproduce-your-issue 

Best
Peter
