### ISSUE TITLE
Pre-script ( for FF)  with IP  Web driver error.

### ISSUE THREAD

**Issue by BPrathap** [sitespeedio/browsertime#635]
While running the pre-script ( for FF) ,  
same login script - https://www.sitespeed.io/documentation/sitespeed.io/prepostscript/ it throws error, when we use  the ip instead of DNS

ex: 
 https://103.102.166.224/w/index.php?title=Special:UserLogin&returnto=Main+Page (it is same as https://en.wikipedia.org/w/index.php?title=Special:UserLogin&returnto=Main+Page)
it is working fine in chrome but not in FF.

**Comment by soulgalore** [comment]
Hey @BPrathap ok, what error do you get and do you run inside of Docker? Seems to be an Firefox issue then, have you checked [Selenium](https://github.com/SeleniumHQ/selenium/issues)/[Geckodriver](https://github.com/mozilla/geckodriver/issues) if there's been similar report?

Best
Peter

**Comment by BPrathap** [comment]
Yes, I have run inside docker.

In login.js

 driver.get('https://some-ip/apps')   // with DNS is able to resolve  
        .then(() => {

This promise is not resolving.



Error:
2018-09-17 05:48:35] ERROR: WebDriverError
    at Object.throwDecodedError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:514:15)
    at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:519:13)
    at doSend.then.response (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.navigate().to(https://10.56.216.116/apps)
    at Driver.schedule (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at Navigation.to (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:1133:25)
    at Driver.get (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:988:28)
    at context.runWithDriver (/performance.ui/container/buildID_19___10.56.216.116/login.js:5:21)
    at SeleniumRunner.runWithDriver (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:276:12)
    at Object.runWithDriver (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:78:24)
    at Object.run (/performance.ui/container/buildID_19___10.56.216.116/login.js:3:20)

**Comment by soulgalore** [comment]
And it is just changing to IP that is the difference? Running with hostname works for FF? Just asking to be 100% because before there has been a difference in Selenium depending on which browser you use and they where slightly different.

**Comment by BPrathap** [comment]
yes,  in pre-script driver.get('https://some-ip/')  this will not resolve in FF (same with DNS it will get resolved)

To test at you end , ping   google.com and get the IP 

return driver.get('https://<google-ip>')
        .then(() => {
          const webdriver = context.webdriver; /*add a debugger*/ - it will never get resolved

**Comment by soulgalore** [comment]
Hey @BPrathap I think the problem is HTTPS and that the certificate will not match the IP.

1. Open Firefox (62).
2. Try http://216.58.211.3
3. Try https://216.58.211.3

Best
Peter

**Comment by soulgalore** [comment]
@BPrathap try with `--firefox.acceptInsecureCerts`, if that doesn't work you need to ask the Firefox team!

Best
Peter

**Comment by soulgalore** [comment]
Think this is a upstream issue that we cannot do anything about.
