### ISSUE TITLE
Getting error while running browsertime 3.12 latest version on GCP 

### ISSUE THREAD

**Issue by sluthra-globallogic** [sitespeedio/browsertime#674]
Error : 
Pre requisite : 

**browsertime version** - 3.12 
**node** - 9.11.1
**npm** - 5.6.0
**google-chrome** - 70.0.3538.102 

**Machine** - GCP 

**Command - /usr/local/bin/browsertime https://www.google.com** 

 **Note: With the same configuration it is working fine on my mac** 
 Please find the logs below 

 

> /root@bbm-demo:~#

 /usr/local/bin/browsertime https://www.google.com
[2018-11-15 07:42:01] INFO: Running chrome for url: https://www.google.com
[2018-11-15 07:42:01] INFO: Testing url https://www.google.com iteration 1
[2018-11-15 07:42:02] INFO: Browser failed to start, trying one more time: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-24-generic x86_64)
[2018-11-15 07:42:02] INFO: Browser failed to start, trying one more time: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-24-generic x86_64)
[2018-11-15 07:42:02] INFO: Browser failed to start, trying one more time: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-24-generic x86_64)
[2018-11-15 07:42:02] ERROR: BrowserError: Could not start the browser with 3 tries
    at SeleniumRunner.start (/usr/local/lib/node_modules/browsertime/lib/core/seleniumRunner.js:81:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
[2018-11-15 07:42:02] INFO: Testing url https://www.google.com iteration 2
[2018-11-15 07:42:02] INFO: Browser failed to start, trying one more time: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-24-generic x86_64)
[2018-11-15 07:42:02] INFO: Browser failed to start, trying one more time: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-24-generic x86_64)
[2018-11-15 07:42:02] INFO: Browser failed to start, trying one more time: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-24-generic x86_64)
[2018-11-15 07:42:02] ERROR: BrowserError: Could not start the browser with 3 tries
    at SeleniumRunner.start (/usr/local/lib/node_modules/browsertime/lib/core/seleniumRunner.js:81:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
[2018-11-15 07:42:02] INFO: Testing url https://www.google.com iteration 3
[2018-11-15 07:42:02] INFO: Browser failed to start, trying one more time: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-24-generic x86_64)
[2018-11-15 07:42:02] INFO: Browser failed to start, trying one more time: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-24-generic x86_64)
[2018-11-15 07:42:02] INFO: Browser failed to start, trying one more time: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-24-generic x86_64)
[2018-11-15 07:42:02] ERROR: BrowserError: Could not start the browser with 3 tries
    at SeleniumRunner.start (/usr/local/lib/node_modules/browsertime/lib/core/seleniumRunner.js:81:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
[2018-11-15 07:42:02] INFO: 0
[2018-11-15 07:42:02] INFO: Wrote data to browsertime-results/www.google.com/2018-11-15T074201+0000
root@bbm-demo:~# "

**Comment by soulgalore** [comment]
Hi @sluthra-globallogic have you started [XVFB](https://linux.die.net/man/1/xvfb) before you started browsertime? Else you need to run headless if you don't setup a screen. If you run our Docker containers XVFB will work automatically.

Best
Peter

**Comment by sluthra-globallogic** [comment]
Hi @soulgalore  I  ran the headless command also but getting the same result  

Command i have used -:
/usr/local/bin/browsertime https://www.google.com --headless  -b chrome

Whereas I have not installed XVFB being a newbie it will be great if you can assist how I can go that way.  But just to inform you on the same GCP chrome headless selenium tests are running very well. 


Regards,
Sukrant Luthra

**Comment by soulgalore** [comment]
Hi again, 
it looks like missmatch between Chrome and Chromedriver?  What you can do is enable chromdriver logging (by adding `--verbose`) and then file an upstream Chromedriver issue.

I think you should try use the Docker container instead, it makes things easier because it's bundled with Chrome/Firefox and the correct drivers.

1. Install Docker
2. `docker run --shm-size=1g --rm -v "$(pwd)":/browsertime sitespeedio/browsertime:3.12.0 https://www.sitespeed.io/`

Best
Peter

**Comment by sluthra-globallogic** [comment]
HI @soulgalore  

Just tried it with docker thing got an issue 

root@bbm-demo:~# docker run --shm-size=1g --rm -v "$(pwd)":/browsertime sitespeedio/browsertime:3.12.0 https://www.sitespeed.io/
WARNING: IPv4 forwarding is disabled. Networking will not work.
Google Chrome 70.0.3538.77 
Mozilla Firefox 63.0
[2018-11-15 08:46:43] INFO: Running chrome for url: https://www.sitespeed.io/
[2018-11-15 08:46:43] INFO: Testing url https://www.sitespeed.io/ iteration 1
[2018-11-15 08:47:07] ERROR: UrlLoadError: Failed to load/verify https://www.sitespeed.io/ uri:chrome-error://chromewebdata/
    at SeleniumRunner.loadAndWait (/usr/src/app/lib/core/seleniumRunner.js:200:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
[2018-11-15 08:47:07] INFO: Testing url https://www.sitespeed.io/ iteration 2

**Comment by soulgalore** [comment]
Try this to enable IPv4: https://stackoverflow.com/questions/41453263/docker-networking-disabled-warning-ipv4-forwarding-is-disabled-networking-wil

**Comment by soulgalore** [comment]
I think this is no BT issue, more on using the environment.
