### ISSUE TITLE
Issue with pageCompleteCheck

### ISSUE THREAD

**Issue by lpeppe** [sitespeedio/browsertime#680]
Hello!
I'm trying to run some benchmarks for an angular app I did. 
The angular app was created for an university project to simulate a very heavy computational load on the client (the page takes 4/5 seconds to fully load).

I'm trying to run sitespeed.io with the pageCompleteCheck flag to wait for the data to show up in the page:
`docker run --shm-size=1g --rm -v "$(pwd)":/sitpeed.io sitespeedio/sitespeed.io http://host.docker.internal:8080/listreplace --browsertime.pageCompleteCheck "return (document.querySelectorAll('body > app-root > listreplace > ul > li').length > 0)"`

but unfortunately the execution halts and does nothing. 

`docker run --shm-size=1g --rm -v "$(pwd)":/sitpeed.io sitespeedio/sitespeed.io http://host.docker.internal:8080/listreplace --browsertime.pageCompleteCheck "return (document.querySelectorAll('body > app-root > listreplace > ul > li').length > 0)"
Google Chrome 70.0.3538.67 
Mozilla Firefox 63.0
[2018-11-26 14:41:21] INFO: Versions OS: linux 4.9.93-linuxkit-aufs nodejs: v8.12.0 sitespeed.io: 7.7.2 browsertime: 3.11.1 coach: 2.4.0
[2018-11-26 14:41:22] INFO: Starting chrome for analysing http://host.docker.internal:8080/listreplace 3 time(s)
[2018-11-26 14:41:22] INFO: Testing url http://host.docker.internal:8080/listreplace iteration 1
`

If I run it without the flag the tests end before the actual data is showed in the page (I checked it from the video). I also tried using --pageCompleteCheckInactivity but it doesn't add enough delay.

**Comment by soulgalore** [comment]
Hi @lpeppe 
ok, I didn't fully get this:
> but unfortunately the execution halts and does nothing.

Do you get an error (like timeout) or do you mean that it doesn't wait for you query? There are some timeouts that are tweak able.

You are sure that the structure isn't there on the page before (I'm just wants to check)? You can also change the log to use verbose `--verbose`  to see if you get something more.

Best
Peter

**Comment by lpeppe** [comment]
Hello Peter, this is what I get with the verbose mode:

`Lucas-MacBook-Pro:Desktop luca$ docker run --shm-size=1g --rm -v "$(pwd)":/sitpeed.io sitespeedio/sitespeed.io http://host.docker.internal:8080/listreplace --browsertime.pageCompleteCheck "return (document.querySelectorAll('body > app-root > listreplace > ul > li').length > 0)" --verbose
Google Chrome 70.0.3538.67 
Mozilla Firefox 63.0
[2018-11-26 18:34:41] INFO: [sitespeedio] Versions OS: linux 4.9.93-linuxkit-aufs nodejs: v8.12.0 sitespeed.io: 7.7.2 browsertime: 3.11.1 coach: 2.4.0
[2018-11-26 18:34:41] INFO: [sitespeedio.plugin.browsertime] Starting chrome for analysing http://host.docker.internal:8080/listreplace 3 time(s)
[2018-11-26 18:34:41] INFO: [browsertime] Testing url http://host.docker.internal:8080/listreplace iteration 1
[2018-11-26 18:34:42] DEBUG: [browsertime.video] Add orange color
[2018-11-26 18:34:42] DEBUG: [browsertime.video] Started ffmpeg with -hide_banner -video_size 1366x642 -f x11grab -framerate 30 -probesize 1M -y -draw_mouse 0 -i :99.0+0,66 -codec:v libx264rgb -crf 0 -preset ultrafast /tmp/browsertime-SMtaxS/x11.mp4
[2018-11-26 18:34:43] DEBUG: [browsertime] Waiting for script pageCompleteCheck at most 300000 ms
[2018-11-26 18:39:43] ERROR: [browsertime] Could not load URLBrowserError: Running page complete check return (document.querySelectorAll('body > app-root > listreplace > ul > li').length > 0) took too long for http://host.docker.internal:8080/listreplace 
[2018-11-26 18:39:43] ERROR: [browsertime] UrlLoadError: Failed to load http://host.docker.internal:8080/listreplace
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:191:13)
    at <anonymous>
[2018-11-26 18:39:43] DEBUG: [browsertime] Kill all processes ffmpeg
[2018-11-26 18:39:43] DEBUG: [browsertime] Telling browser to quit.
[2018-11-26 18:39:43] INFO: [browsertime] Testing url http://host.docker.internal:8080/listreplace iteration 2
[2018-11-26 18:39:44] DEBUG: [browsertime.video] Add orange color
[2018-11-26 18:39:44] DEBUG: [browsertime.video] Started ffmpeg with -hide_banner -video_size 1366x642 -f x11grab -framerate 30 -probesize 1M -y -draw_mouse 0 -i :99.0+0,66 -codec:v libx264rgb -crf 0 -preset ultrafast /tmp/browsertime-vVITgD/x11.mp4
[2018-11-26 18:39:46] DEBUG: [browsertime] Waiting for script pageCompleteCheck at most 300000 ms
[2018-11-26 18:44:45] ERROR: [browsertime] Could not load URLBrowserError: Running page complete check return (document.querySelectorAll('body > app-root > listreplace > ul > li').length > 0) took too long for http://host.docker.internal:8080/listreplace 
[2018-11-26 18:44:45] ERROR: [browsertime] UrlLoadError: Failed to load http://host.docker.internal:8080/listreplace
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:191:13)
    at <anonymous>
[2018-11-26 18:44:45] DEBUG: [browsertime] Kill all processes ffmpeg
[2018-11-26 18:44:45] DEBUG: [browsertime] Telling browser to quit.
[2018-11-26 18:44:45] INFO: [browsertime] Testing url http://host.docker.internal:8080/listreplace iteration 3
[2018-11-26 18:44:46] DEBUG: [browsertime.video] Add orange color
[2018-11-26 18:44:46] DEBUG: [browsertime.video] Started ffmpeg with -hide_banner -video_size 1366x642 -f x11grab -framerate 30 -probesize 1M -y -draw_mouse 0 -i :99.0+0,66 -codec:v libx264rgb -crf 0 -preset ultrafast /tmp/browsertime-4tYc53/x11.mp4
[2018-11-26 18:44:47] DEBUG: [browsertime] Waiting for script pageCompleteCheck at most 300000 ms
[2018-11-26 18:49:47] ERROR: [browsertime] Could not load URLBrowserError: Running page complete check return (document.querySelectorAll('body > app-root > listreplace > ul > li').length > 0) took too long for http://host.docker.internal:8080/listreplace 
[2018-11-26 18:49:47] ERROR: [browsertime] UrlLoadError: Failed to load http://host.docker.internal:8080/listreplace
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:191:13)
    at <anonymous>
[2018-11-26 18:49:47] DEBUG: [browsertime] Kill all processes ffmpeg
[2018-11-26 18:49:47] DEBUG: [browsertime] Telling browser to quit.
[2018-11-26 18:49:47] INFO: [browsertime] 0
[2018-11-26 18:49:47] DEBUG: [plugin.browsertime] Generate summary metrics from Browsertime
[2018-11-26 18:49:47] DEBUG: [plugin.coach] Generate summary metrics from the Coach
[2018-11-26 18:49:47] DEBUG: [plugin.pagexray] Generate summary metrics from PageXray
[2018-11-26 18:49:47] DEBUG: [sitespeedio.plugin.html] Render HTML for 1 page(s) 
[2018-11-26 18:49:47] DEBUG: [sitespeedio.plugin.html] Render summary page errors
[2018-11-26 18:49:48] DEBUG: [sitespeedio.plugin.html] Render summary page pages
[2018-11-26 18:49:48] DEBUG: [sitespeedio.plugin.html] Render summary page index
[2018-11-26 18:49:48] DEBUG: [sitespeedio.plugin.html] Render summary page detailed
[2018-11-26 18:49:48] DEBUG: [sitespeedio.plugin.html] Render summary page domains
[2018-11-26 18:49:48] DEBUG: [sitespeedio.plugin.html] Render summary page assets
[2018-11-26 18:49:48] DEBUG: [sitespeedio.plugin.html] Render summary page toplist
[2018-11-26 18:49:48] DEBUG: [sitespeedio.plugin.html] Render summary page help
[2018-11-26 18:49:48] DEBUG: [sitespeedio.plugin.html] Render URL page index
[2018-11-26 18:49:49] INFO: [sitespeedio.plugin.html] HTML stored in /sitespeed.io/sitespeed-result/host.docker.internal/2018-11-26-18-34-41
[2018-11-26 18:49:49] INFO: [sitespeedio] Finished analysing http://host.docker.internal:8080/listreplace
Lucas-MacBook-Pro:Desktop luca$ 
`

If you want to reproduce the issue I have a repo with the project:
https://github.com/MeCammarano/RG

These are the steps to make it work:

- cd angular
- npm install
- npm run build
- npm run serve:browser

After serving it you can run the docker command

**Comment by lpeppe** [comment]
Yes, it looks like some kind of deadlock

**Comment by lpeppe** [comment]
I tried the javascript code inside chrome console after the page has been loaded and it returns true

**Comment by soulgalore** [comment]
Can you try it in the none docker version locally on your machine? When Chrome is open for 5 minutes, you could open the console and try the code there.

Best
Peter

**Comment by lpeppe** [comment]
I tried the npm version but I couldn't make the video feature work. Do you know why?

**Comment by soulgalore** [comment]
Run it without the video :) To get it to work, you need to have all dependencies on your machine: https://hub.docker.com/r/sitespeedio/visualmetrics-deps/~/dockerfile/

**Comment by lpeppe** [comment]
Can I get the last visual change metric without the video?

**Comment by soulgalore** [comment]
When you find out why the JavaScript isn't working you can switch to use the Docker container.

**Comment by lpeppe** [comment]
it works fine when running sitespeed.io with npm

**Comment by soulgalore** [comment]
Ah sorry no that looks right. Are you sure (like really sure) you reach your page inside of Docker? https://www.sitespeed.io/documentation/sitespeed.io/docker/#access-localhost

**Comment by lpeppe** [comment]
I'm sure it loads the page because I can see the webpage from the video recorded.

**Comment by soulgalore** [comment]
@beenanner do you have any idea of what can be the problem?

**Comment by soulgalore** [comment]
Is this still an issue? Have a hard time seeing that this is something that we can do in Browsertime to fix this.

**Comment by lpeppe** [comment]
Nope, me and my team managed to pass the exam 😂
