### ISSUE TITLE
If page timeout, full tests fails

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#778]
We got a pattern that if the page complete check fails ...
```
[2019-02-18 20:18:52] ERROR: Failed to wait BrowserError: Running page complete check 
return (function(waitTime) { ...
```

We don't collect the timings, and then it fail later on for the HAR:

```
[2019-02-18 20:20:04] ERROR: TypeError: Cannot read property 'timings' of undefined
    at addExtraFieldsToHar (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:71:27)
    at Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:164:7)
```

**Comment by soulgalore** [comment]
We also have this one:
```
[2019-02-18 19:03:46] ERROR: TypeError: Cannot set property '_meta' of undefined
    at Object.addExtrasToHAR (/usr/src/app/node_modules/browsertime/lib/support/har/index.js:145:34)
    at addExtraFieldsToHar (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:67:19)
```

**Comment by soulgalore** [comment]
This has been fixed in the latest releases.
