### ISSUE TITLE
Runtime error when trying running multiple docker instances.

### ISSUE THREAD

**Issue by phongiswindy** [sitespeedio/browsertime#797]
When running several docker containers parallely, I get this RUNTIME ERROR, not sure how to fix it.

> `_XSERVTransMakeAllCOTSServerListeners: server already running
> (EE)
> Fatal server error:
> (EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)
> 
> _XSERVTransMakeAllCOTSServerListeners: server already running
> (EE)
> Fatal server error:
> (EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)
> 
>     at ChildProcess.self._process.on (/usr/src/app/node_modules/@cypress/xvfb/index.js:189:23)
>     at ChildProcess.emit (events.js:182:13)
>     at maybeClose (internal/child_process.js:962:16)
>     at Socket.stream.socket.on (internal/child_process.js:381:11)
>     at Socket.emit (events.js:182:13)
>     at Pipe._handle.close (net.js:606:12)
> `

**Comment by phongiswindy** [comment]
Oops, sorry for clicking wrong button that triggered the issue closed/re-opened. I could solved this problem by assing different display port for different instances using the flag `--xvfbParams.display`
