### ISSUE TITLE
getting timeout error on windows for latest browsertime

### ISSUE THREAD

**Issue by manojs1978** [sitespeedio/browsertime#845]
<!--
getting below error after running command on windows 10 machine

 browsertime https://www.sitespeed.io/

error:
 
$ browsertime https://www.sitespeed.io/
[2019-05-29 10:52:17] INFO: Running tests using Chrome - 3 iteration(s)
[2019-05-29 10:57:26] ERROR: TimeoutError: timeout
  (Session info: chrome=74.0.3729.169)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.16299 x86_64)
  (Session info: chrome=74.0.3729.169)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.16299 x86_64)
    at Object.checkLegacyResponse (C:\Users\*****\AppData\Roaming\npm\node_modules\browsertime\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Users\*****\AppData\Roaming\npm\node_modules\browsertime\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\Users\*****\AppData\Roaming\npm\node_modules\browsertime\node_modules\selenium-webdriver\lib\http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.navigate().to(data:text/html;charset=utf-8,)
    at Driver.schedule (C:\Users\*****\AppData\Roaming\npm\node_modules\browsertime\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
    at Navigation.to (C:\Users\*****\AppData\Roaming\npm\node_modules\browsertime\node_modules\selenium-webdriver\lib\webdriver.js:1133:25)
    at Driver.get (C:\Users\*****\AppData\Roaming\npm\node_modules\browsertime\node_modules\selenium-webdriver\lib\webdriver.js:988:28)
    at Iteration.run (C:\Users\*****\AppData\Roaming\npm\node_modules\browsertime\lib\core\engine\iteration.js:137:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-05-29 10:57:26] ERROR: No data to collect

**Comment by manojs1978** [comment]
getting below error with latest browsertime on windows 10 machine

$ browsertime https://www.sitespeed.io/
[2019-05-29 10:52:17] INFO: Running tests using Chrome - 3 iteration(s)
[2019-05-29 10:57:26] ERROR: TimeoutError: timeout
  (Session info: chrome=74.0.3729.169)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.16299 x86_64)
  (Session info: chrome=74.0.3729.169)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.16299 x86_64)
    at Object.checkLegacyResponse (C:\Users\*****\AppData\Roaming\npm\node_modules\browsertime\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Users\*****\AppData\Roaming\npm\node_modules\browsertime\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\Users\*****\AppData\Roaming\npm\node_modules\browsertime\node_modules\selenium-webdriver\lib\http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.navigate().to(data:text/html;charset=utf-8,)
    at Driver.schedule (C:\Users\*****\AppData\Roaming\npm\node_modules\browsertime\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
    at Navigation.to (C:\Users\*****\AppData\Roaming\npm\node_modules\browsertime\node_modules\selenium-webdriver\lib\webdriver.js:1133:25)
    at Driver.get (C:\Users\*****\AppData\Roaming\npm\node_modules\browsertime\node_modules\selenium-webdriver\lib\webdriver.js:988:28)
    at Iteration.run (C:\Users\*****\AppData\Roaming\npm\node_modules\browsertime\lib\core\engine\iteration.js:137:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-05-29 10:57:26] ERROR: No data to collect

**Comment by soulgalore** [comment]
Hi @manojs1978 not sure, I usually don't dig into Windows problems since https://www.sitespeed.io/documentation/sitespeed.io/installation/#windows-1 but if you have any idea what it can be it would be great to share!

Best
Peter

**Comment by manojs1978** [comment]
after deleteing chrome.dll and reinstalling chrome again , my issue got resolved
