### ISSUE TITLE
Multi page script fails in single page app

### ISSUE THREAD

**Issue by skhilko** [sitespeedio/browsertime#847]
I may be doing something wrong, but from what I read in the [docs on SPA](https://www.sitespeed.io/documentation/sitespeed.io/spa/), the following is supposed to work.

### Script (voicerecordpro.js)
```js
module.exports = async function(context, commands) {
  await commands.measure.start("https://voicerecordpro.com/#/recordings");
  await commands.measure.start("https://voicerecordpro.com/#/community");
  return commands.measure.start("https://voicerecordpro.com/#/favorites");
};
```
### Command
```
docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:9.2.0 voicerecordpro.js --multi --spa -n 1
```
### Result (Error)
```
Google Chrome 74.0.3729.169 
Mozilla Firefox 67.0
[2019-06-01 14:44:30] INFO: Versions OS: linux 5.1.4-arch1-1-ARCH nodejs: v10.15.3 sitespeed.io: 9.2.0 browsertime: 5.1.3 coach: 3.5.7
[2019-06-01 14:44:30] INFO: Running tests using Chrome - 1 iteration(s)
[2019-06-01 14:44:31] INFO: Testing url https://voicerecordpro.com/#/recordings iteration 1
[2019-06-01 14:44:38] INFO: Testing url https://voicerecordpro.com/#/community iteration 1
[2019-06-01 14:44:45] INFO: Testing url https://voicerecordpro.com/#/favorites iteration 1
[2019-06-01 14:44:58] ERROR: TypeError: Cannot set property '_meta' of undefined
    at Object.addMetaToHAR (/usr/src/app/node_modules/browsertime/lib/support/har/index.js:138:34)
    at addExtraFieldsToHar (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:76:19)
    at Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:189:7)
[2019-06-01 14:44:58] INFO: HTML stored in /sitespeed.io/sitespeed-result/voicerecordpro_js/2019-06-01-14-44-30
```

Am I doing this right? I appreciate your help!

**Comment by soulgalore** [comment]
Hi @skhilko I think I had a go but forgot to write an answer sorry. At the moment you need to either navigate or make one request between start/stop for it to work.

Best
Peter

**Comment by jyoprakashJP** [comment]
Hi Peter,
I am facing the similar issue. 
I am doing addToCart trasaction which calls an API, nothing else changes on the page (no navigation). if I add some navigation , it works, but this would not let me capture addToCart timing. any other work around?

**Comment by soulgalore** [comment]
Hi @jyoprakashJP in the coming release you can add data yourself. It's only alpha yet and no docs but you could maybe hack it yourself if you use the latest alpha:

Checkout as an example:
https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/axe/axePostScript.js#L20-L23

But you still then need to measure that API call, and add it to the result yourself. I can make sure that we display metrics automatically that lives in that namespace (we don't do that today). 

Best
Peter

**Comment by 789dry** [comment]
Hi @soulgalore ,is this issue solved?can you give some more detail,thanks.

**Comment by soulgalore** [comment]
If you want to measure other things than navigation you can use the new stop watch command.
