### ISSUE TITLE
Error - code: 28,   state: 'script timeout',

### ISSUE THREAD

**Issue by NITEMAN** [sitespeedio/browsertime#92]
I'm using browsertime as part of sitespeed.io (with latest docker image), with most of the urls I test everything is fine (using firefox, chrome is a different story)... but I can't get www.autobild.es timed (despite WPT seems to have no issues timming it).

This is the full command+output:
~~~
# docker run --privileged --rm -v /opt/dashboard.sitespeed.io/sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io --seleniumServerp://127.0.0.1:4444/wd/hub --resultBaseDir /tmp/ --connection cable --no-html --phantomjsPath /usr/local/phantomjs/bin/phantomjs -b firefox -d 0 -n 3 -u http://www.autobild.es
Mon Aug  3 15:57:40 UTC 2015
ChromeDriver 2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf)
Google Chrome 43.0.2357.81 
Mozilla Firefox 39.0
Starting Xvfb ...
Starting Selenium server ... access it at http://127.0.0.1:4444/wd/hub
info: OS: 'linux 3.16.0-4-amd64', Node.js: 'v0.10.25', sitespeed.io: '3.7.2', PhantomJS: '2.0.0', java: '1.7.0_79', browsertime: '0.10.2'
info: Will analyze 1 page
info: Running YSlow for http://www.autobild.es [phantomjs]
Starting proxy on port 2001, will wait at most 15000 ms
info: Queueing browsertime for http://www.autobild.es firefox
info: Running browsertime for firefox http://www.autobild.es
Fetching http://www.autobild.es (1 of 3)
{ code: 28,
  state: 'script timeout',
  message: 'Timed out waiting for page load.\nBuild info: version: \'2.46.0\', revision: \'87c69e2\', time: \'2015-06-04 16:16:47\'\nSystem info: host: \'0534c1a9596f\', ip: \'172.17.4.73\', os.name: \'Linux\', os.arch: \'amd64\', os.version: \'3.16.0-4-amd64\', java.version: \'1.7.0_79\'\nDriver info: driver.version: unknown',
  name: 'ScriptTimeoutError',
  stack: 'ScriptTimeoutError: Timed out waiting for page load.\nBuild info: version: \'2.46.0\', revision: \'87c69e2\', time: \'2015-06-04 16:16:47\'\nSystem info: host: \'0534c1a9596f\', ip: \'172.17.4.73\', os.name: \'Linux\', os.arch: \'amd64\', os.version: \'3.16.0-4-amd64\', java.version: \'1.7.0_79\'\nDriver info: driver.version: unknown\n    at new bot.Error (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/error.js:108:18)\n    at Object.bot.response.checkResponse (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/response.js:109:9)\n    at /usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:379:20\n    at promise.ControlFlow.runInFrame_ (eval at <anonymous> (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:1857:20)\n    at goog.defineClass.notify (eval at <anonymous> (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:2448:25)\n    at promise.Promise.notify_ (eval at <anonymous> (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:564:12)\n    at Array.forEach (native)\n    at promise.Promise.notifyAll_ (eval at <anonymous> (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:553:15)\n    at goog.async.run.processWorkQueue [as _onTimeout] (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/async/run.js:125:21)\n    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)' }
error: Error running browsertime: { code: 28,
  state: 'script timeout',
  message: 'Timed out waiting for page load.\nBuild info: version: \'2.46.0\', revision: \'87c69e2\', time: \'2015-06-04 16:16:47\'\nSystem info: host: \'0534c1a9596f\', ip: \'172.17.4.73\', os.name: \'Linux\', os.arch: \'amd64\', os.version: \'3.16.0-4-amd64\', java.version: \'1.7.0_79\'\nDriver info: driver.version: unknown',
  name: 'ScriptTimeoutError',
  stack: 'ScriptTimeoutError: Timed out waiting for page load.\nBuild info: version: \'2.46.0\', revision: \'87c69e2\', time: \'2015-06-04 16:16:47\'\nSystem info: host: \'0534c1a9596f\', ip: \'172.17.4.73\', os.name: \'Linux\', os.arch: \'amd64\', os.version: \'3.16.0-4-amd64\', java.version: \'1.7.0_79\'\nDriver info: driver.version: unknown\n    at new bot.Error (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/error.js:108:18)\n    at Object.bot.response.checkResponse (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/response.js:109:9)\n    at /usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:379:20\n    at promise.ControlFlow.runInFrame_ (eval at <anonymous> (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:1857:20)\n    at goog.defineClass.notify (eval at <anonymous> (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:2448:25)\n    at promise.Promise.notify_ (eval at <anonymous> (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:564:12)\n    at Array.forEach (native)\n    at promise.Promise.notifyAll_ (eval at <anonymous> (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:553:15)\n    at goog.async.run.processWorkQueue [as _onTimeout] (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/async/run.js:125:21)\n    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)' }
Stopping proxy
error: Could not generate HAR for http://www.autobild.es { [Error: ENOENT, no such file or directory '/tmp/www.autobild.es/2015-08-03-15-57-41/data/har/firefox/www.autobild.es.har']
  errno: 34,
  code: 'ENOENT',
  path: '/tmp/www.autobild.es/2015-08-03-15-57-41/data/har/firefox/www.autobild.es.har',
  syscall: 'open' }
info: Done analyzing urls
info: Wrote results to /tmp/www.autobild.es/2015-08-03-15-57-41
info: The analyze took 4 minutes (212 seconds)
~~~

**Comment by soulgalore** [comment]
Hi @NITEMAN ,
thanks for the bug report. I think (but haven't tested myself) the problem is that the window.performance.timing.loadEventEnd is never fired (you can check that in your browser you want). It works like this: By default running through sitespeed.io we wait for the loadEventEnd to happen + 2 seconds. You can change that (if your page for some reason doesn't fire the event with the <code>--waitScript</code> parameter.

You can check it out here:
http://www.sitespeed.io/documentation/browsers/#choose-when-to-end-your-test

Best
Peter

**Comment by NITEMAN** [comment]
Hi @soulgalore ,

Thank you for the information and the patience (I'm a sysadmin and use to live far far away from the browsers realm).

You're right and window.performance.timing.loadEventEnd is never fired... but I don't know which event to wait for :(

Watching for window.performance in Chrome I've got:
~~~
connectEnd: 1438772729105
connectStart: 1438772729084
domComplete: 0
domContentLoadedEventEnd: 0
domContentLoadedEventStart: 0
domInteractive: 0
domLoading: 1438772729299
domainLookupEnd: 1438772729084
domainLookupStart: 1438772729061
fetchStart: 1438772729058
loadEventEnd: 0
loadEventStart: 0
navigationStart: 1438772729058
redirectEnd: 0
redirectStart: 0
requestStart: 1438772729105
responseEnd: 1438772729165
responseStart: 1438772729124
secureConnectionStart: 0
unloadEventEnd: 1438772729151
unloadEventStart: 1438772729126
~~~

I'm wondering if something like:
~~~
--waitScript "if (window.performance && window.performance.timing){ return (((window.performance.timing.loadEventEnd > 0) && ((new Date).getTime() - window.performance.timing.loadEventEnd > 2000 )) || ((new Date).getTime() - window.performance.timing.requestStart > 58000);} else { return true;}"
~~~
will catch such cases before reaching 'script timeout'

Best
Pedro

**Comment by soulgalore** [comment]
Hi Pedro,
np :) 

Hmm, that is hard. You will not be able to change/add something on the site right? Best solution for this is to add timinings using the User Timing API so you can define yourself when you want to finish (for example when a specific image is loaded.

However, tested the site now and loadEventEnd is fired after a while, so it should work (and it happens way before 60 seconds (that's our default timeout). Could it be something on the site that was completely broken when you tested (you did get domComplete 0), something like a important resource that timed out/was unreachable.

All the best
Peter

**Comment by NITEMAN** [comment]
Hi Peter,

I'll be able to force changes on the site... in a future :(

I've only tested window.performance in a real browser yesterday (just learned!), but I've been firing sitespeed command each 15 minutes for more than a week and always got the same error.

I thought it's a browsertime issue, but maybe it's sitespeed or the docker image. I don't know how to test browsertime alone yet.

Best regards,
Pedro

**Comment by soulgalore** [comment]
Hi Pedro,
I can check out the problem page more tomorrow, I think it can have something 2do with some reqest that is failing (maybe how the ads are implemented etc) but need to check to know.

Best
Peter

**Comment by NITEMAN** [comment]
Hi Peter,

Tanks again for your support!!!

Anyway, feel free to close the issue... I don't want to steal your time if there  is no issue with browsertime and the problem is only on the tested site.

Best
Pedro

**Comment by parangsjo** [comment]
Hi,

I saw you last achievements, and I think you need to keep up the good work! Here is some helpful information for you <http://tatilovu.miraclemktg.com/xyqjtqhk>

Typos courtesy of my iPhone, pa@rangsjo.com
