### ISSUE TITLE
Opening new window

### ISSUE THREAD

**Issue by javiergarciacotado** [sitespeedio/browsertime#963]
Hi all,

First of all, we are new to browsertime and maybe what we are going to describe next, is not an issue at all (our apologies in advance!).

- Browsertime version: **6.1.3**
- Browser: **Chrome 72**
- BaseURL: http://10.120.188.116/Infinity
- Scenario: Through an extension, the above URL opens in a new browser window, the pages we 
   would like to measure: basically, login and other pages.
- Issue: We have not found the way to switch to new Window before delegating execution to browsertime

- Steps:

1. Using --script option: 

```
_browsertime --chrome.chromedriverPath="chromedriver.exe" --extension="browser-extension-1.0.7-signed.crx" --script="login.js" -n 1 http://10.120.188.116/Infinity_
```

Contents of **login.js**:

```
module.exports = async function(context, commands) {

  context.log.info("[login {start}]");

  try {
    //tried to force navigation to reach this point
    await commands.navigate('http://10.120.188.116/csp/acb/LISPages/LISPages.Main.Login.cls');

  } catch (e) {
    context.log.error('can we handle the exception? ' + e);
  }
};
```
Output:

```
DevTools listening on ws://127.0.0.1:9222/devtools/browser/5abdac90-e78b-4317-b9a3-c77aa81207d4
[2019-10-20 08:55:46] INFO: Testing url http://10.120.188.116/Infinity iteration 1
**[2019-10-20 08:55:49] ERROR: Failed to wait NoSuchWindowError: no such window: target window already closed
from unknown error: web view not found**
  (Session info: chrome=72.0.3626.109)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17763 x86_64)
[2019-10-20 08:55:49] ERROR: Could not load URLUrlLoadError: Failed to wait
[2019-10-20 08:55:49] ERROR: UrlLoadError: Failed to load http://10.120.188.116/Infinity
    at SeleniumRunner.loadAndWait (C:\Users\garcj173\AppData\Roaming\npm\node_modules\browsertime\lib\core\seleniumRunner.js:228:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-10-20 08:55:49] INFO: http://10.120.188.116/Infinity
[2019-10-20 08:55:49] INFO: Wrote data to browsertime-results\10.120.188.116-Infinity\2019-10-20T085537+0200
```

2.  Using --prescript and --script options:

```
browsertime --chrome.chromedriverPath="chromedriver.exe" --extension="browser-extension-1.0.7-signed.crx" --preScript="load.js" --script="login.js" -n 1 http://10.120.188.116/Infinity
```

Contents of **load.js**:

```
module.exports = async function(context, commands) {

    context.log.info("[loading infinity {start}]");
    
    try {
    let driver = context.selenium.driver;
  
    let windowHandles = {
      oldTab: '',
      newTab: ''
    };
  
    await driver.get('http://10.120.188.116/Infinity').then(() => {
      context.log.info('opened?'); //Not opened at all
    });
  
    await driver.getWindowHandle().then(handle => {
      windowHandles.oldTab = handle;
      context.log.info('handle ' + handle);  //it handles only the main window
    });
  
    await driver.getAllWindowHandles().then(handles => {
      windowHandles.newTab = handles[1];
      context.log.info("handles[1] is " + handles[1]);
      return driver.switchTo().window(windowHandles.newTab); //cannot switch as have not opened the new window
    })
    .then(() => {
      return driver.get("http://10.120.188.116/csp/acb/LISPages/LISPages.Main.Login.cls");
    })
  
    context.log.info("[loading infinity {done}]");
  
  } catch (e) {
    context.log.error("is my controlled exception?" + e);
  }
  
};
```

Output:

```
DevTools listening on ws://127.0.0.1:9222/devtools/browser/1130441e-6ee7-44eb-aa76-68b0c5568b8f
**[2019-10-20 09:39:39] INFO: [loading infinity {start}]
[2019-10-20 09:39:42] INFO: opened?
[2019-10-20 09:39:42] INFO: handle CDwindow-40E703C1C1238DD8C70F0DC9F9928131
[2019-10-20 09:39:42] INFO: handles[1] is undefined
[2019-10-20 09:39:42] ERROR: is my controlled exception?InvalidArgumentError: invalid argument: 'name' must be a string**
  (Session info: chrome=72.0.3626.109)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17763 x86_64)
**[2019-10-20 09:39:42] INFO: Testing url http://10.120.188.116/Infinity iteration 1
[2019-10-20 09:39:43] ERROR: Could not load URLNoSuchWindowError: no such window: window was already closed
  (Session info: chrome=72.0.3626.109)**
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17763 x86_64)
[2019-10-20 09:39:43] ERROR: UrlLoadError: Failed to load http://10.120.188.116/Infinity
    at SeleniumRunner.loadAndWait (C:\Users\garcj173\AppData\Roaming\npm\node_modules\browsertime\lib\core\seleniumRunner.js:228:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-10-20 09:39:43] INFO: http://10.120.188.116/Infinity
[2019-10-20 09:39:43] INFO: Wrote data to browsertime-results\10.120.188.116-Infinity\2019-10-20T093930+0200
```

We have tried the latest version with the same result
Many thanks,
Javi

**Comment by soulgalore** [comment]
Hi @javiergarciacotado I haven't done that with Selenium myself, and I think you should have a look in the Selenium user group: https://www.seleniumhq.org/support/ 

Maybe some one did the same before or if you could ask there.

If you get that to work, I'm not 100% sure everything will work though, since today most things I tested with just one main window testing that. For Chrome I think the trace log we use to generate the HAR can/would break. Maybe Firefox would work.

Best
Peter

**Comment by javiergarciacotado** [comment]
hi! Thanks for your quick reply and apologies for my late response...

Even we were able to manage it through SeleniumJS, we are not confident to suggest that PR on the solution due to is only required by us ( most of others use cases will be measuring an url by 1 browser).

I am closing this issue.
Apologies for the inconvenience.
Cheers,
Javi
