### ISSUE TITLE
window recorder for Firefox gives HAR errors

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#983]
Since I enabled the window recorder on our test server, I see many of these kind of errors:

```
[2019-11-04 06:18:48] INFO: Running tests using Firefox - 3 iteration(s)
[2019-11-04 06:18:51] INFO: Testing url https://en.wikipedia.org/wiki/Main_Page iteration 1
[2019-11-04 06:18:51] INFO: Start firefox window recorder.
[2019-11-04 06:18:58] INFO: Stop firefox window recorder.
[2019-11-04 06:18:59] INFO: Waiting on har-export-trigger to collect the HAR
[2019-11-04 06:18:59] ERROR: Could not get the HAR from Firefox JavascriptError: ReferenceError: HAR is not defined
    at Object.throwDecodedError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:560:13)
    at Executor.execute (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:486:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Driver.execute (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:699:17)
    at async FirefoxDelegate.onCollect (/usr/src/app/node_modules/browsertime/lib/firefox/webdriver/firefoxDelegate.js:80:25)
    at async Measure.collect (/usr/src/app/node_modules/browsertime/lib/core/engine/command/measure.js:296:5)
    at async /usr/src/app/node_modules/browsertime/lib/core/engine/run.js:9:9
    at async Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:162:9)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:121:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:125:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:134:24)
```

**Comment by soulgalore** [comment]
I think this is memory related. When I switched to run fewer tests, it seems that we don't get them, so often (or at all).

**Comment by soulgalore** [comment]
Also this:
```
[2019-11-04 13:55:11] INFO: Start firefox window recorder.
[2019-11-04 13:55:11] ERROR: JavascriptError: TypeError: document.body is null
    at Object.throwDecodedError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:560:13)
    at Executor.execute (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:486:26)
```

I think that document.body is from when we add the orange frame?

**Comment by soulgalore** [comment]
Hi @dpalmeiro is this something you have seen on your end? This seems it only happens when I enable the window recorder.

The first errors it seems like the HAR exporter isn't injecting the code correctly and the second one is at start of the navigation, I think where we add the orange layer before we start the navigation.

I'm only seeing these errors when I enable the window recorder, don't know how though but somehow it impacts these two things.

Best
Peter

**Comment by dpalmeiro** [comment]
Hi @soulgalore, unfortunately I'm unable to reproduce this locally on my end with nightly or release.  Could I grab some more information about your test environment to try and reproduce?  Thanks!

**Comment by soulgalore** [comment]
Hi @dpalmeiro  yeah its same here it's just fails sometime, I can't reproduce it on demand. We're running on Digital Ocean Ubuntu 19 but inside our Docker containers. Is there a way I can get some more logs that could help you see what it is? Its turned off at the moment since I'm away, but I can turn it on when I get back in the end of the week.

**Comment by dpalmeiro** [comment]
Perhaps we can start with a -vvv log?  Thanks!

**Comment by soulgalore** [comment]
This needs https://github.com/sitespeedio/browsertime/issues/1027 to be fixed first.

**Comment by soulgalore** [comment]
I think this has been fixed now with @gmierz fixes.
